### ISSUE TITLE
mosquitto_pub message-expiry-interval usage

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/mosquitto#1546] opened 2019-12-31 12:01 UTC
### Description
I am trying to use mosquitto_pub/mosquitto_sub to test message-expiry-interval property. It appears there is bug in implementation of mosquitto_pub or _sub.  I tried using other language clients with mosquitto and message expiry worked correctly. But some thing appears wrong with mosquitto_pub. 

### Version
Mosquitto: 1.6.8
Mosquitto Pub: mosquitto_pub version 1.6.3 running on libmosquitto 1.6.3.
OS: macOS 10.13

### Steps.
1. `mosquitto_sub -t T -c -i X -q 2 -V mqttv5`  //create persistent session for client X
2. `mosquitto_pub -D publish message-expiry-interval 100 -t T -m hello -q 2 -V mqttv5` //publish message A with expiry of 100 seconds
3. `mosquitto_sub -t T -c -i X -q 2 -V mqttv5` //expect reception of message hello 

Here we receive no message in step 3.

**Comment by ralight** [comment] 2020-01-29 16:23
This is an interesting case. The problem comes about because in MQTT v5, the meaning of the clean session flag changed. In MQTT v3.1 and v3.1.1 when the flag is set to 0 it means both "do not clean an existing session when I log in", and "when I disconnect, do not clean my session". In v5 when it is set to 0, it only means "do not clean an existing session when I log in". The removal of the session when the client disconnects is handled by the "session expiry interval" property, which can be set on the connect or disconnect commands.

The mosquitto_pub and _sub tools follow this behaviour, so your first mosquitto_sub command will expire immediately after you quit. If you use the command below then it will work as you expect.

```
mosquitto_sub -t T -c -i X -q 2 -V mqttv5 -D connect session-expiry-interval 100
```

Now to my mind this is a bug because we've changed the expected behaviour of the `-c` argument depending on whether it is a v3 or v5 client. I think it should be changed to match v3, and another easier way of setting the session expiry added. I've summarised the different combinations of clean start and session expiry in the table below, along with how you would achieve that effect now, plus a proposed new command line argument for session expiry. What do you think?

| clean start | expiry interval | current args | proposed args |
| :---: | :---: | --- | --- |
| 1 | 0 | None | None / `-x 0` |
| 1 | N | `-D connect session-expiry-interval N` | `-x N` |
| 1 | Infinite |`-D connect session-expiry-interval 4294967296`| `-x -1` |
| 0 | 0 |`-c`| `-c -e 0` |
| 0 | N |`-c -D connect session-expiry-interval N`| `-c -x N` |
| 0 | infinite |`-c -D connect session-expiry-interval 4294967296`| `-c` / `-c -x -1` |

**Comment by kiranpradeep** [comment] 2020-01-29 21:01
Thanks for the detailed explanation which helped in correct understanding of clean session flag. I could be easily wrong on any of below, please feel free to do it the way you feel best without further explanations. I did little reading on clean start/session. This article [1] gave an impression like: it is not that meaning of clean session has changed. I felt more like clean session is no more part of v5. What is part of v5, is clean start [2]. Based on that view, what I prefer will be - to be more explicit
1. The flag `-c` retains its existing meaning for v3. But, usage of flag `-c` with v5 will throw friendly error message
2. New flag introduced for mqttv5: `--cleanstart` which corresponds of clean start. Usage of `--cleanstart` with v3 will throw friendly error message.
3. Usage of flag `-x` as defined for v5.

[1] https://medium.com/@emqtt/mqtt-5-0-new-feature-clean-start-and-session-expiry-interval-748d4b1a2a95
[2] https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901039

**Comment by ralight** [comment] 2020-01-30 11:02
Interestingly `-c` meant "disable clean start" rather than "disable clean session" originally for MQTT v3, before it changed to clean session in MQTT v3.1.

I disagree with your suggestion for `-c` and `--cleanstart`, I think it is confusing to have different behaviour for the two different protocol versions. With my suggestion, `-c` does the same thing for both protocol versions - disable cleaning of sessions on connect, and setting the session to never expire. The fact that the mechanism that it achieves this is different in the two protocol versions is not important. Likewise not providing `-c` behaves the same in both cases, with sessions being cleaned on connect, and sessions expiring immediately on disconnect. Consistency of behaviour is really really important, you'll have to have a very compelling argument to persuade me otherwise.

**Comment by ralight** [comment] 2020-02-06 16:17
I think that is all fixed now, so I'm going to close this.

**Closed by ralight** 2020-02-06 16:17 UTC
