### ISSUE TITLE
I wanna know if a client is online or not not by last will message

### ISSUE THREAD

**Issue by jake2009** [eclipse/mosquitto#513] opened 2017-08-09 10:05 UTC
I knew that if client use last will ，then I can manage this client online state .
but I donot wanna client to send last will to manage client state .
I hope someone can code this : 
if a client is connect or disconnet then send a message to $SYS/broker/clients/connection/state 
message like this {"clientId","12323","state":"offline"} or  {"clientId","12323","state":"online"}
I cannot use C  to code this by myself 
so any body can help me？

**Comment by diegovisentin** [comment] 2017-08-09 10:39
It's a workaround but you can write a script that reads mosquitto.log to find when a client connect/disconnect and than notify this information to someone (maybe publishing it as you suggested)

**Comment by ralight** [comment] 2017-08-09 20:17
Hi @jake2009 - as you've already seen on #255 this has been discussed before. This isn't something that is being planned to go into the broker. The pull request at #255 has what you need though, so you can take that and use it in your own environment.

I'm closing this because it is a duplicate of #255.

**Closed by ralight** 2017-08-09 20:17 UTC
