### ISSUE TITLE
Mosquitto 1.4.15: Socket error on client 'xxx', disconnecting.

### ISSUE THREAD

**Issue by dxGuan** [eclipse/mosquitto#875] opened 2018-07-03 03:24 UTC
We are currently using mosquitto as a MQTT Broker to push message to multi Application clients which of them are basically mobiles.

For majority of these devices, they work fine, no matter connecting to the broker or sub/pub message(s).

However, I found that some device(s) cannot just work as fine as the others during their connection.

Here are the logs from the mosquitto when they tried to connect to the broker:

1530576623: Client iPhone_13624578 disconnected.
1530576623: New client connected from 172.16.88.101 as iPhone_13624578 (c0, k60, u'13624578').
1530576722: Outgoing messages are being dropped for client iPhone_13624578.
1530576953: Client iPhone_13624578 has exceeded timeout, disconnecting.
1530576953: Socket error on client iPhone_13624578, disconnecting.
1530577076: Client iPhone_13624578 disconnected.
1530577076: New client connected from 172.16.88.101 as iPhone_13624578 (c0, k60, u'13624578').
1530577215: Outgoing messages are being dropped for client iPhone_13624578.
1530577464: Client iPhone_13624578 has exceeded timeout, disconnecting.
1530577464: Socket error on client iPhone_13624578, disconnecting.
1530578071: Client iPhone_13624578 disconnected.
1530578071: New client connected from 172.16.88.101 as iPhone_13624578 (c0, k60, u'13624578').
1530578161: Client iPhone_13624578 has exceeded timeout, disconnecting.
1530578161: Socket error on client iPhone_13624578, disconnecting.

Is it broker side problem or a client side problem?
How to fix it?

**Comment by Tifaifai** [comment] 2018-07-04 06:57
Have you testing an upgrade to mosquitto 1.5 ? 
The idea is to be able to concentrate development efforts on the latest version

**Comment by dxGuan** [comment] 2018-07-05 00:49
@Tifaifai Alright, we will give it a shot and let's see whether it will be solved or not.

**Comment by toast-uz** [comment] 2018-07-27 12:53
What's going on this issue? Close this issue if you cannot convince the cause is at mosquitto.

**Comment by toast-uz** [comment] 2018-09-09 03:48
Closing as no information for a long time. Feel free to reopen if you are having this issue yet.

**Closed by toast-uz** 2018-09-09 03:48 UTC
Labels: need-more-information

**Comment by ZaitsevS** [comment] 2019-02-14 08:21
I have same problem

**Comment by ralight** [comment] 2019-02-14 12:33
```
1545268762: Client LEDstrip has exceeded timeout, disconnecting.
```

This means that your client has not communicated with the broker within the keepalive it configured (15 seconds), so the broker disconnected it. This is not a problem with mosquitto, it is your client that you need to look at.

**Comment by fmvin** [comment] 2019-02-22 11:32
I have the same problem. This happens only if  mosquitto and client program are started from rc.local. If the client is killed and started again manually this problem is not repeated.
`
New client connected from 127.0.0.1 as mosq/ciKalXMsU4u=dlC_wb (c1, k3).
1550586971: No will message specified.
1550586971: Sending CONNACK to mosq/ciKalXMsU4u=dlC_wb (0, 0)
1550586971: Client mosq/ciKalXMsU4u=dlC_wb already connected, closing old connection.
1550586971: Socket error on client mosq/ciKalXMsU4u=dlC_wb, disconnecting.
1550586971: New client connected from 127.0.0.1 as mosq/ciKalXMsU4u=dlC_wb (c1, k3).
1550586971: No will message specified.
1550586971: Sending CONNACK to mosq/ciKalXMsU4u=dlC_wb (0, 0)
1550586971: New connection from 127.0.0.1 on port 1883.
1550586971: No will message specified.
1550586971: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586971: 	lk/regime (QoS 0)
1550586971: mosq/ciKalXMsU4u=dlC_wb 0 lk/regime
1550586971: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586971: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586971: 	lk/camc/right (QoS 0)
1550586971: mosq/ciKalXMsU4u=dlC_wb 0 lk/camc/right
1550586971: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586971: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586971: 	lk/camc/rs/rcv/right (QoS 0)
1550586971: mosq/ciKalXMsU4u=dlC_wb 0 lk/camc/rs/rcv/right
1550586971: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586971: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586971: 	lk/camc/debug/right (QoS 0)
1550586971: mosq/ciKalXMsU4u=dlC_wb 0 lk/camc/debug/right
1550586971: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586972: Client mosq/ciKalXMsU4u=dlC_wb already connected, closing old connection.
1550586972: Socket error on client mosq/ciKalXMsU4u=dlC_wb, disconnecting.
1550586972: New client connected from 127.0.0.1 as mosq/ciKalXMsU4u=dlC_wb (c1, k3).
1550586972: No will message specified.
1550586972: Sending CONNACK to mosq/ciKalXMsU4u=dlC_wb (0, 0)
1550586972: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586972: 	lk/regime (QoS 0)
1550586972: mosq/ciKalXMsU4u=dlC_wb 0 lk/regime
1550586972: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586972: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586972: 	lk/camc/bottom (QoS 0)
1550586972: mosq/ciKalXMsU4u=dlC_wb 0 lk/camc/bottom
1550586972: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586972: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586972: 	lk/camc/rs/rcv/bottom (QoS 0)
1550586972: mosq/ciKalXMsU4u=dlC_wb 0 lk/camc/rs/rcv/bottom
1550586972: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586972: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586972: 	lk/camc/debug/bottom (QoS 0)
1550586972: mosq/ciKalXMsU4u=dlC_wb 0 lk/camc/debug/bottom
1550586972: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586973: New connection from 127.0.0.1 on port 1883.
1550586973: Client mosq/ciKalXMsU4u=dlC_wb already connected, closing old connection.
1550586973: Socket error on client mosq/ciKalXMsU4u=dlC_wb, disconnecting.
1550586973: New client connected from 127.0.0.1 as mosq/ciKalXMsU4u=dlC_wb (c1, k3).
1550586973: No will message specified.
1550586973: Sending CONNACK to mosq/ciKalXMsU4u=dlC_wb (0, 0)
1550586973: Client mosq/hsPO7Ws^[2gxYQhdsK already connected, closing old connection.
1550586973: Socket error on client mosq/hsPO7Ws^[2gxYQhdsK, disconnecting.
1550586973: New client connected from 127.0.0.1 as mosq/hsPO7Ws^[2gxYQhdsK (c1, k3).
1550586973: No will message specified.
1550586973: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586973: 	lk/regime (QoS 0)
1550586973: mosq/ciKalXMsU4u=dlC_wb 0 lk/regime
1550586973: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586973: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586973: 	lk/camc/right (QoS 0)
1550586973: mosq/ciKalXMsU4u=dlC_wb 0 lk/camc/right
1550586973: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586973: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586973: 	lk/camc/rs/rcv/right (QoS 0)
1550586973: mosq/ciKalXMsU4u=dlC_wb 0 lk/camc/rs/rcv/right
1550586973: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586973: Received SUBSCRIBE from mosq/ciKalXMsU4u=dlC_wb
1550586973: 	lk/camc/debug/right (QoS 0)
1550586973: mosq/ciKalXMsU4u=dlC_wb 0 lk/camc/debug/right
1550586973: Sending SUBACK to mosq/ciKalXMsU4u=dlC_wb
1550586974: New connection from 127.0.0.1 on port 1883.
1550586974: Client mosq/ciKalXMsU4u=dlC_wb already connected, closing old connection.
1550586974: Socket error on client mosq/ciKalXMsU4u=dlC_wb, disconnecting.
1550586974: New client connected from 127.0.0.1 as mosq/ciKalXMsU4u=dlC_wb (c1, k3).
1550586974: No will message specified.
1550586974: Sending CONNACK to mosq/ciKalXMsU4u=dlC_wb (0, 0)
1550586974: New connection from 127.0.0.1 on port 1883.
`
