### ISSUE TITLE
bridge: lost outgoing messages with clean_session=true and local_clean_session=false

### ISSUE THREAD

**Issue by kervel** [eclipse/mosquitto#2604] opened 2022-08-04 13:30 UTC
running on mosquitto 2.0.11

situation: local mosquitto bridges outgoing messages to remote mosquitto. also some incoming messages but the incoming messages are not important and don't have to be persisted, only the outgoing. the "remote" mosquitto is actually multiple mosquitto's running in failover without shared state so sessions cannot be persisted on the remote side reliably (each replica is also running a kafka connect instance). However, i don't want to loose local outgoing messages.

so, i set clean_session to true (so that the remote broker doesn't have to queue messages for the local one) but local_cleansession to false (because i don't want to loose outgoing messages).

however, i still seem to loose outgoing messages. When connectivity drops, i see mosquitto.db growing as expected, and if connectivity resumes, all queued messages are sent out. But when i restart mosquitto, the mosquitto.db seems to get emptied.

**Comment by ralight** [comment] 2022-08-13 21:48
Thanks for the report and nice explanation. I've found the cause and pushed a fix to the `fixes` branch if you wish to try it out. I intend to release it as part of 2.0.15 on Monday.

**Closed** 2022-08-16 14:53 UTC
Labels: Type: Bug, Component: mosquitto-broker, Status: Completed
