### ISSUE TITLE
Missing Flow Limiting on outgoing messages

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#58] opened 2016-03-15 00:57 UTC
migrated from Bugzilla [#466928](https://bugs.eclipse.org/bugs/show_bug.cgi?id=466928)
status UNCONFIRMED severity _normal_ in component _Mosquitto_ for _1.4_
Reported in version _unspecified_ on platform _All_
Assigned to: Roger Light

On 2015-05-10 06:52:51 -0400, Christoph Krey wrote:

> Server may overflow Client
> 
> Situation:
> - A client subscribes to a topic which receives a few hundred messages per hour with qos > 0 and cleansession = NO.
> - The client goes off-line for a while.
> - When the client reconnects to mosquitto, mosquitto publishes those hundreds of messages to the client.
> - The client cannot PUBACK to all of the messages in a timely manner.
> - This causes the majority of the messages to be retransmitted after retry_interval 20 (default) seconds.
> 
> Depending on the number of queued messages, the message size and the available band-with lead to:
> - unneccessary multiple transmissions
> -     a waste of possible expensive band-with (mobile data plans)
> - possibly memory overflows
> - connection aborts
> 
> On mobile clients with limited bandwidth, a flow control or flow limiting approach seems appropriate.
> The MQTT standard does not address this topic.
> 
> In the library, a window size (n) for outgoing PUBLISH messages would be desirable: When qos > 0, only n messages are sent before the corresponding acknowledge is received (PUBACK or PUBREC/PUBREL/PUBCOMP).
> A meaningful window size may differ for different client types (mosquitto.conf).

**Comment by PierreF** [comment] 2017-12-29 17:32
I can't reproduce this issue. From my understanding of the issue, it is fixed: the broker sent at most max_inflight_messages (20 by default) messages and wait for the first PUBACK before sending the next messages.
Therefor the only way I see for message retry to happen is if the client take more than 20 seconds to acknowledged a message. Another possibility is that could client take more than 1 seconds to process one message and to it's processing sequentially. In this case the 20th message will be acknowledged only after more than 20 seconds (1 seconds * 20 messages).

If your client is unable to reply within 20 seconds retry_interval should be increased. If your client process messages sequentially and took more than 1 seconds, you should either reduce max_inflight_messages or increase retry_interval.

I'm closing the issue, since max_inflight_messages is enforced.

**Closed by PierreF** 2017-12-29 17:32 UTC
Labels: bug, mosquitto-broker
