### ISSUE TITLE
a mosquitto server can accept how many devices?

### ISSUE THREAD

**Issue by myie9** [eclipse/mosquitto#582] opened 2017-10-09 01:04 UTC
if one device publish a message per 5 seconds.
And the server's hardware requrement is what?  4G ram is ok?

**Comment by toast-uz** [comment] 2017-10-09 10:55
Could you post such a question at mosquitto-dev ML? This place is for bugs.

**Comment by PierreF** [comment] 2018-01-04 11:08
Closing as not a bug. Guidances are better ask on [Mosquitto ML](https://dev.eclipse.org/mailman/listinfo/mosquitto-dev). On the ML other users may share their usage and how they handled the scaling. Keep in mind that use case may vary (size of message, number of consumers, speed of consumer/publisher, ...) and will probably require you to do your own benchmark anyway.

**Closed by PierreF** 2018-01-04 11:08 UTC
