### ISSUE TITLE
Connection with Minio doesn't work because of client ID being empty string

### ISSUE THREAD

**Issue by tkislan** [eclipse/mosquitto#1543] opened 2019-12-18 21:26 UTC
This is related (or same issue) to https://github.com/eclipse/mosquitto/issues/291
But that issue was closed, and I'm not sure if it's tracked anywhere

log output
```
1576701761: New connection from 172.18.0.9 on port 1883.
1576701761: Sending CONNACK to 172.18.0.9 (0, 2)
1576701761: Client <unknown> disconnected due to protocol error.
```

https://github.com/minio/minio/blob/9bb0869b737df8c2eb8a1451910581dee01fc72d/pkg/event/target/mqtt.go#L210
Removing this line makes it work

log output
```
1576703356: New connection from 172.18.0.9 on port 1883.
1576703356: New client connected from 172.18.0.9 as auto-3FE14366-E165-AB3F-4B54-2CB3F1EBD563 (p2, c1, k0, u'minio').
1576703356: No will message specified.
```

**Comment by ralight** [comment] 2019-12-18 22:23
There are a few situations where this can occur.

1. If you are using MQTT v3 or v3.1, then zero length client ids are forbidden.

2. If you are connecting with MQTT v3.1.1, then zero length clients ids are forbidden if you have clean session set to false.

3. If you have `allow_zero_length_clientid` set to false then zero length client ids are forbidden.

All of those are valid and expected behaviour.

If looks like you are using MQTT v3.1.1 (`p2` in the CONNECT string) with clean session set to true (`c1` in the CONNECT string), which would suggest that you have `allow_zero_length_clientid` set to false. Please do check this.

Could you please check that clean session is set to true? This is the most likely point to be causing the problem.

**Comment by tkislan** [comment] 2019-12-19 17:55
Yes, you can see that in provided link from minio repo
```
SetCleanSession(true)
```

Also, I have `allow_zero_length_clientid true` in mosquitto config

**Comment by ralight** [comment] 2019-12-21 00:11
Do you think you could capture the problem CONNECT packet being sent by the client using wireshark/tcpdump?

**Comment by ralight** [comment] 2020-01-30 16:06
Any news on getting a packet capture?

**Comment by ralight** [comment] 2020-04-30 09:29
I've tried to reproduce this with the Paho golang client, and the only way I can get it to display the same behaviour is to set `allow_zero_length_clientid false` in the config file. This is the only code path that exists. I've tested on 1.3.5, 1.4.15, 1.5.9, and all of the 1.6.x releases using the default configuration (i.e. no config file). They all worked as expected, allowing the client to connect.

I don't believe this is a bug in Mosquitto, so I'm closing the issue. If it is still a problem for you, please reopen and provide more details.

**Closed by ralight** 2020-04-30 09:29 UTC
