### ISSUE TITLE
test.mosquitto.org + phpMQTT = Connection refused

### ISSUE THREAD

**Issue by kazuser** [eclipse/mosquitto#907] opened 2018-08-02 13:53 UTC
![untitled12](https://user-images.githubusercontent.com/3335273/43588018-63754e8e-968d-11e8-9b20-d09e1ee45d18.png)

When I'm trying create connection (from typical shared hosting to test.mosquitto.org) with [phpMQTT](https://github.com/bluerhinos/phpMQTT), I'm getting an error **Connection refused** - why? And how to fix it?

**Comment by ralight** [comment] 2018-08-02 20:27
Could you try connecting with another tool? If that works then you know the problem is with phpMQTT. If it doesn't work - then can you access http://test.mosquitto.org in your browser?

If that doesn't work - then perhaps you have a network problem. It works just fine for me using mosquitto_sub and with the web.

**Comment by kazuser** [comment] 2018-08-03 05:16
Hi! Thank you for reply!

**1**. I've tried with [MQTT](https://github.com/walkor/mqtt) already - [the same result](https://github.com/walkor/mqtt/issues/2) :(

**2**. What about test.mosquitto.org in browser: look, I'm with my browser somethere in Kazakhstan - my shared hosting somethere in Europe. I'm just trying to subscribe to %topic% on far-far-away-shared-hosting with cpanel/php/console onboard - please don't forget ;) Anyway, here are the screens from my PC (not from shared hosting - so I think it useless at all):

![000](https://user-images.githubusercontent.com/3335273/43624613-64d68c5c-970a-11e8-9f4f-1030cf33717d.gif)

**3**. I didn't knew about "mosquitto_sub" before today, thanks a lot! My task is: all I need is view/monitor everything in my %topic% in <24/7/365> mode. But I can't use my own mobile devices for direct connection in any time in any place. And I can install nothing to my hosting - I can simply use the already available (rules of hosting). So if I understand a "mosquitto_sub" correctly - I just can copy the php-files to my hosting and use it and subscribe to any topic and view any incoming message in any time?

**Comment by ralight** [comment] 2018-08-08 08:44
Соединение было Сброшено - connection was reset. You can't connect to port 1883 with a browser because the browser talks http and port 1883 is mqtt.

Are you sure that your ISP or hosting provider allows you to make connections to port 1883? It certainly seems as though you are being denied at the network level if multiple tools produce the same result.

**Comment by ralight** [comment] 2018-09-25 14:30
I don't believe this is a bug in mosquitto, so I'm closing it. If you're still having problems please reopen it and provide more details.

**Closed by ralight** 2018-09-25 14:30 UTC
