### ISSUE TITLE
mosquitto_passwd - Fails to append users after initial user - v2.0.16 - Windows

### ISSUE THREAD

**Issue by BookSwapSteve** [eclipse/mosquitto#2882] opened 2023-08-24 02:27 UTC
Version: 2.0.16
OS: Windows Server 2019

Steps to reproduce:
* Create an initial user (non-existent password file): mosquitto_passwd -c -b C:\path-to\passwordfile user1 [user1 password]
* Inspect passwordfile observing that user1 has been added
* Add a second user to the existing file: mosquitto_passwd -b C:\path-to\passwordfile user2 [user2 password]
* Observe no errors are raised
* Inspect passwordfile observing that user2 has **not** been added
* Try again without batch mode: mosquitto_passwd C:\path-to\passwordfile user2
* Observe we are **not prompted** for the user2 password to use and no entry is added and no error was raised.

I've not been able to test 2.0.17 as the binary didn't appear to be available on the download site, so this may be fixed already. 

I reverted to 2.0.15 I was able to created users as expected.

**Comment by karlp** [comment] 2023-08-24 11:16
Duplicate of #2873 fixed in https://github.com/eclipse/mosquitto/blob/v2.0.17/ChangeLog.txt#L10

**Comment by ralight** [comment] 2023-09-12 23:08
The changelog message is different, but Karl is correct this was fixed in 2.0.17. Thanks for the report!

**Closed by ralight** 2023-09-12 23:08 UTC
