### ISSUE TITLE
Mosquitto Service Shows Active (exited) Upon New Install - Missing CONF File

### ISSUE THREAD

**Issue by JZ-SmartThings** [eclipse/mosquitto#641] opened 2017-12-05 21:01 UTC
Hi, having an install issue with brand new Xubuntu 17.10... the /etc/mosquitto/mosquitto.conf file never gets created and it causes the service to hang with **active (exited)** status of the service and the TCP port is not listening. Please see examples below. Adding a simple conf file with **persistence false** then restarting the service easily fixes the problem. Thank you!

```
hass@NASHASS:/etc$ sudo apt install mosquitto
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libev4 libwebsockets8
The following NEW packages will be installed:
  libev4 libwebsockets8 mosquitto
0 upgraded, 3 newly installed, 0 to remove and 42 not upgraded.
Need to get 208 kB of archives.
After this operation, 572 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://us.archive.ubuntu.com/ubuntu artful/universe amd64 libev4 amd64 1:4.22-1 [26.3 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu artful/universe amd64 libwebsockets8 amd64 2.0.3-3 [71.8 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu artful/universe amd64 mosquitto amd64 1.4.12-1 [110 kB]
Fetched 208 kB in 10s (19.5 kB/s)
Selecting previously unselected package libev4.
(Reading database ... 188599 files and directories currently installed.)
Preparing to unpack .../libev4_1%3a4.22-1_amd64.deb ...
Unpacking libev4 (1:4.22-1) ...
Selecting previously unselected package libwebsockets8:amd64.
Preparing to unpack .../libwebsockets8_2.0.3-3_amd64.deb ...
Unpacking libwebsockets8:amd64 (2.0.3-3) ...
Selecting previously unselected package mosquitto.
Preparing to unpack .../mosquitto_1.4.12-1_amd64.deb ...
Unpacking mosquitto (1.4.12-1) ...
Setting up libev4 (1:4.22-1) ...
Setting up libwebsockets8:amd64 (2.0.3-3) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for libc-bin (2.26-0ubuntu2) ...
Setting up mosquitto (1.4.12-1) ...
Processing triggers for systemd (234-2ubuntu12.1) ...
Processing triggers for man-db (2.7.6.1-2) ...
hass@NASHASS:/etc$ ls -lot /etc/mosquitto/
total 12
drwxr-xr-x 2 root 4096 Dec  5 12:19 conf.d
drwxr-xr-x 2 root 4096 Dec  5 12:19 certs
drwxr-xr-x 2 root 4096 Dec  5 12:19 ca_certificates
hass@NASHASS:/etc$ sudo /etc/init.d/mosquitto status
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; generated; vendor preset: enabled)
   Active: active (exited) since Tue 2017-12-05 12:20:01 PST; 2min 31s ago
     Docs: man:systemd-sysv-generator(8)
Dec 05 12:20:01 NASHASS systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Dec 05 12:20:01 NASHASS mosquitto[15754]:  * Starting network daemon: mosquitto
Dec 05 12:20:01 NASHASS mosquitto[15754]:    ...done.
Dec 05 12:20:01 NASHASS systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
hass@NASHASS:/etc$ sudo /etc/init.d/mosquitto stop
[ ok ] Stopping mosquitto (via systemctl): mosquitto.service.
hass@NASHASS:/etc$ netstat -an|grep 1883
hass@NASHASS:/etc$
```

AFTER CREATING MOSQUITTO.CONF WITH ONLY PERSISTENCE FALSE AT THE TOP
--------------------------------------------------------------------
```
hass@NASHASS:/etc$ sudo /etc/init.d/mosquitto status
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; generated; vendor preset: enabled)
   Active: active (running) since Tue 2017-12-05 12:24:39 PST; 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 16686 ExecStop=/etc/init.d/mosquitto stop (code=exited, status=0/SUCCESS)
  Process: 16749 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/mosquitto.service
           └─16756 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

Dec 05 12:24:39 NASHASS systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Dec 05 12:24:39 NASHASS mosquitto[16749]:  * Starting network daemon: mosquitto
Dec 05 12:24:39 NASHASS mosquitto[16749]:    ...done.
Dec 05 12:24:39 NASHASS systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
hass@NASHASS:/etc$ netstat -an|grep 1883
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN
tcp6       0      0 :::1883                 :::*                    LISTEN

```

--------------------------------------------------------------------

AFTER REMOVING THE CONF FILE AGAIN
--------------------------------------------------------------------
```
hass@NASHASS:/etc$ sudo /etc/init.d/mosquitto status
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; generated; vendor preset: enabled)
   Active: active (exited) since Tue 2017-12-05 12:35:45 PST; 16s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 17065 ExecStop=/etc/init.d/mosquitto stop (code=exited, status=0/SUCCESS)
  Process: 17072 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)

Dec 05 12:35:45 NASHASS systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Dec 05 12:35:45 NASHASS mosquitto[17072]:  * Starting network daemon: mosquitto
Dec 05 12:35:45 NASHASS mosquitto[17072]:    ...done.
Dec 05 12:35:45 NASHASS systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
hass@NASHASS:/etc$ netstat -an|grep 1883
hass@NASHASS:/etc$
```

**Comment by karlp** [comment] 2017-12-05 21:12
This looks like a bug in the ubuntu packaging. See the line 
```
Get:3 http://us.archive.ubuntu.com/ubuntu artful/universe amd64 mosquitto amd64 1.4.12-1 [110 kB]
```

You might have more luck filing this in ubuntu's bug tracker.  (bright side, at least ubuntu has stopped shipping 0.15!)

**Comment by JZ-SmartThings** [comment] 2017-12-05 22:14
I see so it's their cached package on ubuntu.com vs. the public version. Begs the question of whether I can add the "real" source (Eclipse, seems to be) and instead grab the installer package from there. Aware of this method by any chance?

**Comment by dboi88** [comment] 2018-01-04 13:48
I'm having this same issue, @JZ-SmartThings did you find any solution?

**Comment by PierreF** [comment] 2018-01-04 17:37
Closing as this looks like a Ubuntu packaging issue and not Mosquitto issue. Feel free to reopen if you think it's a Mosquitto issue.

That being said, it's not the package itself that had an issue (a fresh install on Ubuntu 17.10 with the same mosquitto version) had the file. But I'm able to reproduce this issue if the following is done:
* install mosquitto
* remove /etc/mosquitto/mosquitto.conf
* uninstall (apt remove) mosquitto
* re-install mosquitto

In this case, Ubuntu packaging will NOT recreate the configuration because it keep your "configuration changes" (the removal of the file).
The only workaround I know it to purge the package (apt purge mosquitto or dpkg --purge mosquitto). Be aware that this will remove the persistence file and all configuration files of mosquitto. If you need to keep them, you have to backup them.

**Closed by PierreF** 2018-01-04 17:37 UTC

**Comment by JZ-SmartThings** [comment] 2018-01-04 18:51
The manual solution is to create /etc/mosquitto/mosquitto.conf and put "persistence true" which is the default but I actually like false so that my momentary switches don't switch on/off when MQTT connects.

Just adding that single key/value to the config file easily started the MQTT services for me.
