### ISSUE TITLE
Standby "H/A" support

### ISSUE THREAD

**Issue by stefannilsson** [eclipse/mosquitto#372] opened 2017-02-05 07:40 UTC
It would have been great of Mosquitto would have supported an active/standby configuration to make underlaying server maintenance not so scary.
By maybe using file locks to indicate if some of the machines within the "availability cluster" is active.

I'm thinking of a solution where, when you start the Mosquitto process if first verifies it's able to get an exclusive file lock of the "mosquitto.db" in order to proceed. If it's not able to do so, it will keep on running and on a scheduled basis check if the file lock is released and then hook it up and start listening to incoming connections.

**Comment by stefannilsson** [comment] 2017-04-09 07:57
Someone with a good insight into the application - how much time do you think, very roughly, would be required to implement something similar as proposed above?

**Comment by toast-uz** [comment] 2017-09-18 07:10
Basically I agree with your wish. But due to MQTT protocol architecture, implementing duplex system is very difficult. We must care QoS packet proceeding, Retain, session persistence (it's similar but different from your comment's persistence-db), and so on.
OASIS MQTT TC considered this in working for MQTT v5, but they postponed due to its difficulty.

**Comment by toast-uz** [comment] 2018-03-02 14:19
Closing because it's not a bug and there is a great challenge for the cluster on mosquitto-dev ML.

**Closed by toast-uz** 2018-03-02 14:19 UTC
Labels: enhancement, mosquitto-broker
