### ISSUE TITLE
Mosquitto cannot decrypt messages from esp8266 and finishes communication

### ISSUE THREAD

**Issue by jayceeZar** [eclipse/mosquitto#764] opened 2018-04-05 09:26 UTC
#### Platform

- Hardware:			ESP8266 Wemos D1 mini

### Settings in IDE

- Module:  			Wemos D1 mini
- Flash Size: 		        4MB
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:              115200

### Problem Description

I'm trying to make a secure connection using TLS through the library Wificlientsecure ( With the library WifiClient it works perfectly). The certificates' exchange is done without problems but the connection never success. In mosquitto's broker i see the following:

```
- New connection from 10.228.54.79 on port 8883.

and some secons after...

- Socket error on client <unknown>, disconnecting.

```

I don't know why the ESP8266 verifies the broker but after a few seconds it aborts it.

mosquitto.conf:

```

allow_anonymous false
password_file /etc/mosquitto/conf.d/passwd

listener 8883

cafile /etc/mosquitto/conf.d/Certificates/mqtt_ca.crt
certfile /etc/mosquitto/conf.d/Certificates/mqtt_server.crt
keyfile /etc/mosquitto/conf.d/Certificates/mqtt_server.key

require_certificate false

```

I generated the certificates following this procedure: 

```
1) Generate a CA certificate and key
sudo openssl req -new -x509 -days 3650 -extensions v3_ca -keyout mqtt_ca.key -out mqtt_ca.crt

2) Generate a server key
sudo openssl genrsa -out mqtt_server.key 2048

3) Generate a certificate signing request to send to the CA
sudo openssl req -out mqtt_server.csr -key mqtt_server.key -new

4) Send the CSR to the CA, or sign it with your CA key
sudo openssl x509 -req -in mqtt_server.csr -CA mqtt_ca.crt -CAkey mqtt_ca.key -CAcreateserial -out mqtt_server.crt -days 3650

```

### Sketch

```cpp

#include <Arduino.h>

void setup() {
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  
  delay(10);

  // initialize the pushbutton pin as an input:
  pinMode(buttonPin3, INPUT_PULLUP);
  attachInterrupt(buttonPin3, push3, FALLING);
  pinMode(buttonPin4, INPUT_PULLUP);
  attachInterrupt(buttonPin4, push4, FALLING);

  // Connect to WiFi access point.
  Serial.println(); Serial.println();
  Serial.print("Connecting to ");
  Serial.println(WLAN_SSID);

  WiFi.begin(WLAN_SSID, WLAN_PASS);
  delay(2000);
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();

  Serial.println("WiFi connected");
  Serial.println("IP address: "); Serial.println(WiFi.localIP());

  SPIFFS.begin();

  //Load CA's certificate
  File ca = SPIFFS.open("/mqtt_caCert.der", "r");

  if (!ca) {
    Serial.println("Failed to open ca file");
  } else {   
    Serial.println("Success to open ca file");
  }
  if(client.loadCACert(ca,ca.size())) {
    Serial.println("loaded");
  } else {
    Serial.println("not loaded");
  }
 
  firstTime3 = millis();

  // Setup MQTT will to set on/off to "0" when we disconnect
  mqtt.will(AIO_USERNAME "/feeds/0003/onoff", "0", 1, 0); // topic, message, qos, retain

  verifyFingerprint();
}

void loop() {

}

void verifyFingerprint() {

  const char* host = AIO_SERVER;

  Serial.print("Connecting to ");
  Serial.println(host);

  if (! client.connect(host, AIO_SERVERPORT)) {
    Serial.println("Connection failed. Halting execution.");
    while(1);
  }

  if (client.verify(fingerprint, host)) {
    Serial.println("Connection secure.");
  } else {
    Serial.println("Connection insecure! Halting execution.");
    while(1);
  }

}

```

### Debug Messages

```
Connecting to SHOPFLOOR2

connected with SHOPFLOOR2, channel 6
dhcp client start...
ip:10.228.54.79,mask:255.255.255.0,gw:10.228.54.1

WiFi connected
IP address: 
10.228.54.79
SPIFFSImpl: allocating 512+240+1400=2152 bytes
SPIFFSImpl: mounting fs @100000, size=2fb000, block=2000, page=100
SPIFFSImpl: mount rc=0
Success to open ca file
=== CERTIFICATE ISSUED TO ===
Common Name (CN):		CAMqtt
Organization (O):		
Organizational Unit (OU):	IT
Location (L):			Zaragoza
Country (C):			ES
State (ST):			Zaragoza
Basic Constraints:		CA:TRUE, pathlen:10000
=== CERTIFICATE ISSUED BY ===
Common Name (CN):		CAMqtt
Organization (O):		
Organizational Unit (OU):	IT
Location (L):			Zaragoza
Country (C):			ES
State (ST):			Zaragoza
Not Before:			Fri Mar 16 10:18:32 2018
Not After:			Mon Mar 13 10:18:32 2028
RSA bitsize:			2048
Sig Type:			SHA256
loaded
Connecting to ESZARASSRVIOT001.eu.net
[hostByName] request IP for: ESZARASSRVIOT001.eu.net
[hostByName] Host: ESZARASSRVIOT001.eu.net IP: 10.228.48.94

State:	sending Client Hello (1)
State:	receiving Server Hello (2)
State:	receiving Certificate (11)
=== CERTIFICATE ISSUED TO ===
Common Name (CN):		ESZARASSRVIOT001.eu.net
Organization (O):		
Organizational Unit (OU):	IT
Location (L):			Zaragoza
Country (C):			ES 
State (ST):			Zaragoza
=== CERTIFICATE ISSUED BY ===
Common Name (CN):		CAMqtt
Organization (O):		
Organizational Unit (OU):	IT
Location (L):			Zaragoza
Country (C):			ES
State (ST):			Zaragoza
Not Before:			Fri Mar 16 10:21:45 2018
Not After:			Mon Mar 13 10:21:45 2028
RSA bitsize:			2048
Sig Type:			SHA256
=== CERTIFICATE ISSUED TO ===
Common Name (CN):		CAMqtt
Organization (O):		
Organizational Unit (OU):	IT
Location (L):			Zaragoza
Country (C):			ES
State (ST):			Zaragoza
Basic Constraints:		CA:TRUE, pathlen:10000
=== CERTIFICATE ISSUED BY ===
Common Name (CN):		CAMqtt
Organization (O):		
Organizational Unit (OU):	IT
Location (L):			Zaragoza
Country (C):			ES
State (ST):			Zaragoza
Not Before:			Fri Mar 16 10:18:32 2018
Not After:			Mon Mar 13 10:18:32 2028
RSA bitsize:			2048
Sig Type:			SHA256

State:	receiving Server Hello Done (14)
State:	sending Client Key Exchange (16)
State:	sending Finished (16)
State:	receiving Finished (16)
domain name: 'ESZARASSRVIOT001.eu.net
Connection secure.
SPIFFS_close: fd=1
:abort

```

### Wireshark capture

```

4	0.008274	10.228.54.79	10.228.48.94	TLSv1.2	167	Client Hello
5 0.008287       10.228.48.94          10.228.54.79          TCP      54     8883 → 49153 [ACK] Seq=1 Ack=114 Win=29200 Len=0
6 0.008482       10.228.48.94          10.228.54.79          TLSv1.2  1126   Server Hello
7 0.008597       10.228.48.94          10.228.54.79          TLSv1.2  1081   Certificate, Server Hello Done
8 0.020484       10.228.54.79          10.228.48.94          TCP      60     49153 → 8883 [ACK] Seq=114 Ack=537 Win=2144 Len=0
15 0.432524       10.228.54.79          10.228.48.94          TLSv1.2  321    Client Key Exchange
16 0.468582       10.228.48.94          10.228.54.79          TCP      54     8883 → 49153 [ACK] Seq=2100 Ack=381 Win=30016 Len=0
17 0.472833       10.228.54.79          10.228.48.94          TLSv1.2  145    Change Cipher Spec, Encrypted Handshake Message
18 0.472846       10.228.48.94          10.228.54.79          TCP      54     8883 → 49153 [ACK] Seq=2100 Ack=472 Win=30016 Len=0
19 0.472998       10.228.48.94          10.228.54.79          TLSv1.2  145    Change Cipher Spec, Encrypted Handshake Message
21 0.895418       10.228.54.79          10.228.48.94          TCP      60     49153 → 8883 [ACK] Seq=472 Ack=2191 Win=2144 Len=0
22 26.884422      10.228.54.79          10.228.48.94          TLSv1.2  139    Application Data
23 26.884535      10.228.48.94          10.228.54.79          TLSv1.2  123    Encrypted Alert
24 26.884587      10.228.48.94          10.228.54.79          TCP      54     8883 → 49153 [FIN, ACK] Seq=2260 Ack=557 Win=30016 Len=0
25 26.926360      10.228.54.79          10.228.48.94          TCP      60     49153 → 8883 [ACK] Seq=557 Ack=2260 Win=2075 Len=0
```

Thanks in advance. I've tried everything, stuck with this for a week.

**Comment by ralight** [comment] 2018-04-05 22:31
Could you try with mosquitto_sub instead, so we can try to isolate the problem?

    mosquitto_sub --cafile mqtt_ca.crt -p 8883 -h ESZARASSRVIOT001.eu.net -t '$SYS/#' -d

Alternatively, maybe use the openssl client:

    openssl s_client -connect ESZARASSRVIOT001.eu.net:8883 -CAfile mqtt_ca.crt -verify_return_error

**Comment by ralight** [comment] 2018-04-06 07:35
Ok, the log in this case it means that neither nodered nor your esp client are sending a client certificate, but that mosquitto expects one. Your config at the top uses `require_certificate false`, is that still the case?

**Comment by jayceeZar** [comment] 2018-04-06 07:48
On the last log, mosquitto.conf is changed to require_certificate true, but i think the main problem is on server's authentication (with require_certificate false), because mosquitto_sub authenticates server and connects with it but ESP8266 aborts the connection.
In case of client's authentication (require_certificate true) it never works, i was wrong (fails with mosquitto_sub, node-red and esp8266), mosquitto ALWAYS  says "OpenSSL Error: error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate
1522941421: Socket error on client <unknown>, disconnecting."

**Comment by ralight** [comment] 2018-04-06 23:27
I'm afraid it sounds like the problem is with the esp client and nodered (or with how you have them configured) rather than with mosquitto.

**Comment by ralight** [comment] 2018-11-07 22:05
This hasn't seen an update for a long while, so I'm going to close it. If it is still an issue for you, please reopen the bug and provide some more details.

**Closed by ralight** 2018-11-07 22:05 UTC
