### ISSUE TITLE
隐式声明 cJSON_CreateStringReference 总是报cjson的错误 

### ISSUE THREAD

**Issue by phplpf** [eclipse/mosquitto#1966] opened 2020-12-18 11:44 UTC
隐式声明 cJSON_CreateStringReference 总是报cjson的错误 
详细报错如下：

/home/xxx/xx/mosquitto/client/sub_client_output.c: In function ‘json_print’:
/home/xxx/xxx/mosquitto/client/sub_client_output.c:265:8: warning: implicit declaration of function ‘cJSON_CreateStringReference’ [-Wimplicit-function-declaration]
  tmp = cJSON_CreateStringReference(buf);
        ^
/home/xxx/xxx/mosquitto/client/sub_client_output.c:265:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  tmp = cJSON_CreateStringReference(buf);
      ^
[ 32%] Building C object client/CMakeFiles/mosquitto_rr.dir/client_shared.c.o
[ 33%] Building C object client/CMakeFiles/mosquitto_rr.dir/client_props.c.o
[ 33%] Linking C executable mosquitto_rr
CMakeFiles/mosquitto_rr.dir/sub_client_output.c.o: In function `json_print':
sub_client_output.c:(.text+0x6f8): undefined reference to `cJSON_CreateStringReference'
/usr/local/lib/libcjson.so: undefined reference to `floor'
collect2: error: ld returned 1 exit status
client/CMakeFiles/mosquitto_rr.dir/build.make:202: recipe for target 'client/mosquitto_rr' failed
make[2]: *** [client/mosquitto_rr] Error 1
CMakeFiles/Makefile2:238: recipe for target 'client/CMakeFiles/mosquitto_rr.dir/all' failed
make[1]: *** [client/CMakeFiles/mosquitto_rr.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ralight** [comment] 2020-12-18 12:44
What version of cJSON do you have installed? The cJSON_CreateStringReference() function appeared in version 1.7.0 of cJSON.

**Comment by ralight** [comment] 2022-08-12 21:31
Closing because I think the issue is not in mosquitto. If you disagree, please reopen and add more information.

**Closed by ralight** 2022-08-12 21:31 UTC
