### ISSUE TITLE
Docker build fails with unsatisfiable constraints.

### ISSUE THREAD

**Issue by chainhead** [eclipse/mosquitto#1711] opened 2020-06-01 16:09 UTC
When this command is run, `docker build -t org/repo/image:1.0.2 --build-arg VERSION="1.5.1" .`, the docker build fails as shown below.

```bash
Step 7/15 : LABEL maintainer="Jonathan Hanson <jonathan@jonathan-hanson.org>" 	description="Eclipse Mosquitto MQTT Broker"
 ---> Running in 768e33ba76a2
Removing intermediate container 768e33ba76a2
 ---> 646ce2592a1e
Step 8/15 : RUN apk --no-cache add       busybox       ca-certificates       libcrypto1.0       libssl1.0       libuuid       libwebsockets       musl
 ---> Running in 8fb517405a01
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libcrypto1.0 (missing):
    required by: world[libcrypto1.0]
  libssl1.0 (missing):
    required by: world[libssl1.0]
The command '/bin/sh -c apk --no-cache add       busybox       ca-certificates       libcrypto1.0       libssl1.0       libuuid       libwebsockets       musl' returned a non-zero code: 2

```

**Comment by chainhead** [comment] 2020-06-01 16:55
It seems that `libcrypto1.0` was available in `3.3` - see [here](https://pkgs.alpinelinux.org/packages?name=libcrypto1.0&branch=v3.3). So, I tried, with base image as `alpine:3.3`. But, `tar --strip=1 -xzC /build` in `Dockerfile` fails.

**Comment by Sumatt92** [comment] 2020-06-01 20:36
It seems like your working from generic dockerfile. To get to run I :
Replaced

libcrypto1.0 \
libssl1.0 \

with 

libressl \

at line 51 in generic/Dockerfile

**Comment by chainhead** [comment] 2020-06-02 02:11
Yes, I did that too. Now, `mosquitto` does not like `log_timestamp_format` variable in the `mosquitto.conf` file; says, it is an unknown variable.

**Comment by Sumatt92** [comment] 2020-06-02 02:43
Hmmm. You are needing a particular version of mosquitto right?
It seems like this generic/dockerfile maybe has several issues that I've not had with the other dockerfiles (I've been playing with the dockerfiles  for my own project).

**Comment by chainhead** [comment] 2020-06-02 04:14
Well, [1.6] `Dockerfile` [fails](https://github.com/eclipse/mosquitto/issues/1712#issue-628886452) too.

**Comment by salvq** [comment] 2020-06-02 15:39
Getting same error while building from generic

`[/share/Download/44] # sudo docker build -t test/eclipse-mosquitto:1.6.9 --build-arg VERSION="1.6.9" .
`
```
Step 8/15 : RUN apk --no-cache add       busybox       ca-certificates       libcrypto1.0       libssl1.0       libuuid       libwebsockets       musl
 ---> Running in cd6f71763fee
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libcrypto1.0 (missing):
    required by: world[libcrypto1.0]
  libssl1.0 (missing):
    required by: world[libssl1.0]
The command '/bin/sh -c apk --no-cache add       busybox       ca-certificates       libcrypto1.0       libssl1.0       libuuid       libwebsockets       musl' returned a non-zero code: 2

```

**Comment by Sumatt92** [comment] 2020-06-02 17:54
Yeah I think there are some issues with the generic dockerfile. 

I think that the generic is there as a catchall to build an image of any published version of mosquitto that does not already have its own dockerfile in the docker/ directory.

It seems like it has some version issues. In particular the first stage is building with the generic names for libs, defaulting to the latest version of them whereas the second stage is using specific versions of libs, and both stages are using the latest version of alpine. This is the cause of the unsatisfiable constraints error. Modifying the generic dockerfile to build a particular version should not be difficult but making the generic dockerfile work consistently for all versions now and into the future may be more challenging.

**Comment by chainhead** [comment] 2020-06-03 01:38
What is the difference between the various versions? I mean how do they correlate with what's on Docker Hub?

**Comment by Sumatt92** [comment] 2020-06-03 02:34
If you just run something like 
`docker pull eclipse-mosquitto`
you will pull the default (the latest) mosquitto image, built and ready to run. You can also pull different versions with
`docker pull eclipse-mosquitto:\<version\>`

[dockerhub mosquitto images](https://hub.docker.com/_/eclipse-mosquitto?tab=tags) show the available images.

The dockerfiles from the mosquitto repo, however, are building the image anew. 
The problem in the generic/dockerfile is stuff like :

```
FROM alpine:latest

RUN apk --no-cache add \
      busybox \
      ca-certificates \
      libcrypto1.0 \
      libssl1.0 \
      libuuid \
      libwebsockets \
      musl
```

which will break when alpine:latest no longer has those specific libraries available from apk (the current libssl is libssl1.1 and I think maybe libcrypto has been rolled into an ssl lib??)

**Comment by salvq** [comment] 2020-06-03 06:34
@Sumatt92 just checked latest pkg list for alpine and you're right, working docker file has to be updated to libcrypto1.1 & libssl1.1 instead of libcrypto1.0 & libssl1.0

Then docker built works fine for actual version, 1.6.9

**Comment by Sumatt92** [comment] 2020-06-06 19:35
#1717

**Comment by ralight** [comment] 2020-06-09 14:26
This is now fixed as per the pull request. Thanks @Sumatt92

**Closed by ralight** 2020-06-09 14:26 UTC
