### ISSUE TITLE
Two clients authenticated with psk connect and disconnect in an infinite loop

### ISSUE THREAD

**Issue by pat1** [eclipse/mosquitto#2590] opened 2022-07-15 16:16 UTC
```
mosquitto_sub -i id1 -h test.rmap.cc -t "1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213" -p 8885 --psk-identity  user --psk 4F4E5E10D2D11AE2C5AC60120F07EFAA -d

mosquitto_sub -i id2 -h test.rmap.cc -t "1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213" -p 8885 --psk-identity  user --psk 4F4E5E10D2D11AE2C5AC60120F07EFAA -d
```
each command disconnect and reconnect

```
Client id2 sending CONNECT
Client id2 received CONNACK (0)
Client id2 sending SUBSCRIBE (Mid: 1, Topic: 1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213, QoS: 0, Options: 0x00)
Client id2 received SUBACK
Subscribed (mid: 1): 0
Client id2 sending CONNECT
Client id2 received CONNACK (0)
Client id2 sending SUBSCRIBE (Mid: 2, Topic: 1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213, QoS: 0, Options: 0x00)
Client id2 received SUBACK
Subscribed (mid: 2): 0
Client id2 sending CONNECT
Client id2 received CONNACK (0)
Client id2 sending SUBSCRIBE (Mid: 3, Topic: 1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213, QoS: 0, Options: 0x00)
Client id2 received SUBACK
Subscribed (mid: 3): 0
Client id2 sending CONNECT
Client id2 received CONNACK (0)
Client id2 sending SUBSCRIBE (Mid: 4, Topic: 1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213, QoS: 0, Options: 0x00)
Client id2 received SUBACK
Subscribed (mid: 4): 0
Client id2 sending CONNECT
Client id2 received CONNACK (0)
Client id2 sending SUBSCRIBE (Mid: 5, Topic: 1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213, QoS: 0, Options: 0x00)
Client id2 received SUBACK
Subscribed (mid: 5): 0
Client id2 sending CONNECT
Client id2 received CONNACK (0)
Client id2 sending SUBSCRIBE (Mid: 6, Topic: 1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213, QoS: 0, Options: 0x00)
Client id2 received SUBACK
Subscribed (mid: 6): 0
Client id2 sending CONNECT
Client id2 received CONNACK (0)
Client id2 sending SUBSCRIBE (Mid: 7, Topic: 1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213, QoS: 0, Options: 0x00)
Client id2 received SUBACK
Subscribed (mid: 7): 0
Client id2 sending CONNECT
Client id2 received CONNACK (0)
Client id2 sending SUBSCRIBE (Mid: 8, Topic: 1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213, QoS: 0, Options: 0x00)
Client id2 received SUBACK
Subscribed (mid: 8): 0
Client id2 sending CONNECT
Client id2 received CONNACK (0)
Client id2 sending SUBSCRIBE (Mid: 9, Topic: 1/report/userv4//1112345,4412345/test/254,0,0/265,0,-,-/B01213, QoS: 0, Options: 0x00)
Client id2 received SUBACK
Subscribed (mid: 9): 0
```
The broker say:
```
Client user already connected, closing old connection.
```

**Comment by ralight** [comment] 2022-08-06 22:06
The only way I can reproduce this is by setting the options:

```
use_identity_as_username true
use_username_as_clientid true
```

Are you using these? If so, then this behaviour is exactly as expected.

**Comment by ralight** [comment] 2022-08-07 20:54
I'm closing this issue because I think I've addressed it sufficiently to answer what you need. I'm trying to close issues like this to get on top of the issues list. If there is still something left to do on this issue, please reopen it and give more details.

**Closed by ralight** 2022-08-07 20:54 UTC
