### ISSUE TITLE
Connect between javascript and mosquitto !!

### ISSUE THREAD

**Issue by PaulTsai20160627** [eclipse/mosquitto#248] opened 2016-08-21 09:04 UTC
Hi : 
I am going to test a basic function of receiving and transmitting messages from html web browser to terminals through mosquitto websocket.First of all, I typed the command that mosquitto supports as shown below:
![image](https://cloud.githubusercontent.com/assets/20158340/17836315/d299bc76-67c0-11e6-9bce-0dbf268964ef.png)
And then wants to send message from html files as  shown below:
![image](https://cloud.githubusercontent.com/assets/20158340/17836330/fc73ac00-67c0-11e6-8406-2bc05dcfa6e9.png)
Then , I want to receive message on the terminals.
Here is one problem that I encountered during testing the html file with javascript. 
My computer always shows that Unable to connect localhost message as I typed
localhost/mqtt_js_demo.html.But If I open it directly from My file folders it can display what I write html content:
![image](https://cloud.githubusercontent.com/assets/20158340/17836294/b6321a98-67bf-11e6-8a3f-ef184fbfec8b.png)

So, First I want to ask is How to let my html file let broswer to see at localhost/mqtt_js_demo.html
Second, If I want I can let html file receive my message from terminals send from mosquitto, how do I do ? 

Following is my source code of html : 

``` javascript
<html>
<meta charset="utf-8">
<title>mqtt js client demo</title>

<script src="mqttws31-min.js"></script>
<script>
const TOPIC = "tw/rocksaying/";
var client = false;

// 用戶端成功連接 broker 時...
function onConnect() {
    // 確認連接後，才能訂閱主題
    console.log("onConnect then subscribe topic");
    client.subscribe(TOPIC + "#");
}

// 收到訊息時...
function onMessageArrived(message) {
    console.log("onMessageArrived:"+message.payloadString);
    document.getElementById("mqtt_monitor").innerHTML = message.payloadString;
}

// 發佈訊息
function publish_message() {
    var input_text = document.getElementById("mqtt_text");
    var payload = input_text.value;
    var message = new Paho.MQTT.Message(payload);
    message.destinationName = TOPIC + "text";
    client.send(message);
    input_text.value = '';
}

function init() {
    document.getElementById("mqtt_pub").addEventListener('click', publish_message);
    // 建立 MQTT 用戶端實體. 你必須正確寫上你設置的埠號.
    // ClientId 可以自行指定，提供 MQTT broker 認證用
    client = new Paho.MQTT.Client("ws://localhost:11883/", "myClientId");

    // 指定收到訊息時的處理動作
    client.onMessageArrived = onMessageArrived;

    // 連接 MQTT broker
    client.connect({onSuccess:onConnect});
}

window.addEventListener('load', init, false);
//document.addEventListener('DOMContentLoaded', init, false);
</script>
<body>
<p>
mqtt client test...
</p>

<div>
<input type="text" id="mqtt_text" />
<button id="mqtt_pub">Publish</button>
</div>

<div id="mqtt_monitor">
</div>

</body>
</html>
```

/etc/mosquitto/mosquitto.conf

``` javascript
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
bind_address localhost
listener 1883
protocol mqtt
listener 8081 127.0.0.1
protocol websockets
http_dir /mnt/pc/projects/robot
```

**Comment by ralight** [comment] 2016-09-20 22:41
It looks like the problem is your code attempts to connect to post 11883 but you are using port 8081 in your configuration.

**Comment by PaulTsai20160627** [comment] 2016-09-21 00:20
Hi : 
After Checking with modifying the 11883 to 8081 or 8081 to 11883 @ this two posistion:

```
/etc/mosquitto/mosquitto.conf

listener 8081 127.0.0.1


html :

client = new Paho.MQTT.Client("ws://localhost:11883/", "myClientId");
```

mosquitto still can not receive the string from the web site. 
I don't know why ? Does it relate to html file because I just open it as a file but no onto the server ?
Or any settings still not set well so ....... ? How to solve this problems?

**Comment by Kinka** [comment] 2016-09-22 08:16
save problem here. Configured with `http_dir /path/to/statics`, the content under http_dir cannot be accessed on the browser. It just returns zero content.

If I run `curl http://127.0.0.1:2883/mqtt.js`, I got 'Empty reply from server'.

mosquitto.conf:
```
listener 2883
protocol websockets
http_dir /var/www
```

contents under /var/www, just one file: mqtt.js

**Comment by PaulTsai20160627** [comment] 2016-09-22 08:41
Hi Kinka:
Can you show me the file mqtt.js is ? I can not help you analyze this problem even though I still solve the previous problem above ! besides, can you clearly describe what you try to do and what's your purpose to do ?

**Comment by ralight** [comment] 2016-09-22 09:28
What version of libwebsockets are you using? Older versions don't support file transfer very well.

**Comment by Kinka** [comment] 2016-09-22 10:29
Hi PaulTsai,
All starts here: [https://mosquitto.org/man/mosquitto-conf-5.html](https://mosquitto.org/man/mosquitto-conf-5.html)
```
http_dir directory
When a listener is using the websockets protocol, it is possible to serve http data as well. Set http_dir to a directory which contains the files you wish to serve. If this option is not specified, then no normal http connections will be possible.
```

I think that means mosquitto can be used as http webserver serving static files if another port listening on protocol websockets rather than mqtt, right?

And @ralight , I downloaded the latest binary version `1.4.10` from mosquitto.org, as the release logs say the libwebsockets v2.x is being used.

So, I tried to serve mqtt.js(whatever its content is, just a text file) under the directory `/var/www` which I set in mosquitto.conf. However, as I described above, the mosquitto webserver replied nothing. The port should be correct or another error occur like `connection refused`.

And sorry for my poor explation, but am I understood now?

**Comment by ssimd** [comment] 2016-11-21 09:12
Hi @Kinka 
see my comment in #286 
I had the same problem with version 1.4.10, but in version 1.4.8 it works.

**Comment by Kinka** [comment] 2016-11-23 03:02
Thanks @ssimd , I will try another version later.

**Comment by ralight** [comment] 2016-12-04 23:07
@Kinka 1.4.10 of mosquitto can use libwebsockets 2.x, but the more important question is which one are you actually using? If you are using <1.7 then I wouldn't want to guarantee that plain http will work.

**Comment by PierreF** [comment] 2018-01-02 14:43
Original issue is not about internal webserver of Mosquitto but only about not being able to connect to MQTT websocket. I think the original issue arise because the page was viewed using file:/// and most if not all browser disable javascript when using file:///.
I'm closing the issue as this is not a Mosquitto issue, if my assumption is false feel free to reopen the issue.

The second issue about internal webserver is tracked under #286 and resolved. Mosquitto must be built with libwebsockets 1.7+ to work with http_dir.

**Closed by PierreF** 2018-01-02 14:43 UTC
