### ISSUE TITLE
Messages are not delivered after 10 reconnects with a persistent session

### ISSUE THREAD

**Issue by maxim-kukushkin** [eclipse/mosquitto#898] opened 2018-07-29 16:55 UTC
When a client stops and starts several times (10 with default Mosquitto configuration) with a persistent session, eventually it doesn't get any messages.

Steps to reproduce:
1. Start mosquitto_sub with a persistent session and QoS 2:
$ mosquitto_sub -q 2 -t test_topic -c -i test_client

2. Send some messages to see that the communication works:
$ mosquitto_pub -q 2 -t test_topic -m test_message

3. Stop the client

4. Repeat the previous steps about 10 times

Eventually the client stops receiving any messages. Restarting the client with different QoS level or a clean session doesn't help. Sending unsubscribe and subscribe requests doesn't help. Changing sent messages QoS doesn't help as well.
Only Mosquitto server restart helps (persistence is configured)

Tried with various clients:
- Built-in mosquitto_sub
- org.fusesource.mqtt-client for Java
- PubSubClient for ESP8266
The behavior is exactly the same

Skipping subscription on further restarts (after the initial subscription requests) doesn't change the behavior. Graceful shutdown doesn't affect it as well (I presume mosquitto_sub shuts down gracefully on Ctrl-C)

When the client in "blocked" in such a way, subscribing to another topic works (again for the next ~10 reconnects).

The root cause of the issue may in theory be related to the one in #874

**Comment by toast-uz** [comment] 2018-07-29 22:57
Could you confirm it is different from #874 ?

**Comment by toast-uz** [comment] 2018-07-29 23:00
Could you try #883 ?

**Comment by maxim-kukushkin** [comment] 2018-07-29 23:46
@toast-uz do you mean, to run the same experiment with mosquitto_sub, but with QoS 1?

As per #874 - I'm just making a guess that the root cause in theory be related, but I don't think it's exactly the same issue

**Comment by toast-uz** [comment] 2018-07-30 03:17
Sorry, I revised my comment, you might answer for old one. Check the issue web page.

**Comment by maxim-kukushkin** [comment] 2018-07-30 21:01
@toast-uz yeah, I noticed, that's why I replied to both versions of your comment.
I just hardly see how #883 applies to the use case I described in this ticket. Do you want me to play with QoS 1 instead?

I believe there's nothing to be changes in my client side code as the issue is reproducible with the provided "mosquitto_sub" tool

**Comment by toast-uz** [comment] 2018-07-30 22:09
I'm sorry again, I had a wrong number, it was #893 . I'd like to confirm #893 can be a remedy for your issue as having similar root cause with #893 's issue.

**Comment by maxim-kukushkin** [comment] 2018-07-31 22:59
@toast-uz I've just tried to check the version of the code in the pull request and it seems to be working - I cannot reproduce the issue with mosquitto_sub and Java client.

Thanks! Looking forward for it to be merged and become available in Arch's pacman repo

**Comment by toast-uz** [comment] 2018-08-01 10:02
Thanks @maxim-kukushkin , keep this issue until #893 merged.

**Comment by ralight** [comment] 2018-08-01 18:40
The PR fixing this has now been merged, and I've added a test for it as well. If you could give the fixes branch a try and comment here, then we can close the issue.

**Comment by maxim-kukushkin** [comment] 2018-08-01 22:43
@ralight yes, I tried the fixes branch and I confirm that the issue is resolved there. Do you already know which version will include the fix so that I can track it in my distro's repository?

**Comment by ralight** [comment] 2018-08-01 23:38
This will be in 1.5.1, thanks for confirming it. What distro are you using?

**Closed by ralight** 2018-08-01 23:38 UTC
Labels: bug, mosquitto-broker

**Comment by maxim-kukushkin** [comment] 2018-08-01 23:44
@ralight 
Thanks!

I'm using Arch Linux
