### ISSUE TITLE
Bridge notifications doesn't publish state 0 on local broker when loosing internet

### ISSUE THREAD

**Issue by pod67** [eclipse/mosquitto#2467] opened 2022-02-25 14:28 UTC
Hi,

I have seen som reports with similar behaviour when having notification_local_only true, but in my case I have notifications turned on both locally and remote.
When shutting down remote bridge the bridge state 0 is published on local broker, but if I instead break the internet connection the bridge will **never** publish state 0!
The remote broker will always detect lost connection with bridge and publish state 0.

### How to reproduce his:
Set up a local broker and a bridge to for example test.mosquitto.org:1883 and notifications = true.
Verify bridge-state-topic to have value 1.
Disconnect your internet-connection (disconnect WiFi or equivalent)
Expected result is bridge state 0, but is still 1.

Noticed behaviour when this occur:
bridge will restart repeatedly, after timeouts, connecting to local broker and will log an error saying that the remote host is unknown, probably caused by no internet connection.

**Comment by pod67** [comment] 2022-03-14 08:51
I ran another test using the IP-address, 5.196.95.208 and now the state changes as expected.
So this points to that the bug is that the failed DNS-lookup is the cause for not setting bridge state down!

**Comment by jsaak** [comment] 2022-03-30 17:51
I have other results.
I use IP instead of hostname, and still no state 0.

**Comment by karlp** [comment] 2022-03-31 12:01
See also https://github.com/eclipse/mosquitto/issues/1488 that this is probably a dupe of.

**Comment by pod67** [comment] 2022-03-31 13:19
Actually #1488 is the post I'm referring to in the first sentence of the first post, and also pointing out the differences.

**Comment by pod67** [comment] 2022-03-31 14:11
I second that solution 1 is preferred.
I would also be happy to test the fix in our IoT-device where we hava a problem with this issue.

**Comment by ralight** [comment] 2022-05-25 15:51
Please give the `develop` branch a try if you are able.

**Comment by BubuOT** [comment] 2022-05-31 20:09
I tried compiling the `fixes` branch which contains the above mentioned commit but it fails with the following error:

```
cc  -I. -I.. -I../include -I../../include -DWITH_TLS -DWITH_TLS_PSK -DWITH_THREADING -DWITH_SOCKS -DWITH_UNIX_SOCKETS -I../deps -Wall -ggdb -O2 -Wconversion -Wextra -fPIC -c util_mosq.c -o util_mosq.o
util_mosq.c: In function ‘mosquitto__check_keepalive’:
util_mosq.c:114:2: error: #else without #if
  114 | #else
      |  ^~~~
util_mosq.c:136:2: error: #endif without #if
  136 | #endif
      |  ^~~~~
make[1]: *** [Makefile:222: util_mosq.o] Error 1
make[1]: Leaving directory '/home/marcus/repos/mosquitto/lib'
make: *** [Makefile:66: mosquitto] Error 2
```

**Comment by ralight** [comment] 2022-06-06 08:54
@BubuOT Sorry about that, it's fixed now.

**Comment by BubuOT** [comment] 2022-06-10 16:00
Tested again now and this seems to fix the problem for us. Thanks for fixing this! (after it was broken 7 years ago I think? :))

**Closed** 2022-08-16 14:53 UTC
