### ISSUE TITLE
Mosquitto 1.5 unable to switch between persistent and clean session

### ISSUE THREAD

**Issue by sxsing** [eclipse/mosquitto#874] opened 2018-07-02 16:40 UTC
When a clean session is started after a persistent session with the same client ID, the broker fails to forget the persistent session.

Here is my test:

1. Start a client to subscribe with QoS=1 and persistent session.
./mosquitto_sub -t topic -i id -q 1 -c

2. Stop the client.

3. Restart the client with clean session. Listen to the same topic.
./mosquitto_sub -t topic -i id -q 1

4. Publish a message to that topic. The broker falsely blocks the message.
./mosquitto_pub -t topic -i id2 -m "hello" -q 0
After executing this command, nothing is received by mosquitto_sub.

Further tests show that, as long as the published topic matches any topic subscribed in persistent session with QoS>0, it will be blocked.

**Comment by karlp** [comment] 2018-07-02 17:02
Looks like #866

**Comment by ckrey** [comment] 2018-07-04 06:18
Agreed, seems like #866 

After this sequence
```
mosquitto_sub -i sub -t 'topic' -v -p 29883 -q 1 -d -c
^C
mosquitto_sub -i sub -t 'topic' -v -p 29883 -q 1 -d 
^C
```

SUBSCRIBE to `topic` is no longer respected by mosquitto

run:
```
mosquitto_sub -i sub -t 'topic' -v -p 29883 -q 1 -d -c
```

and in a separate shell
```
mosquitto_pub -i pub -t topic -m 'hello' -p 29883 -q 1
```
`sub` does not receive the message


mosquitto.log
```
1530684790: New connection from 10.0.2.2 on port 1883.
1530684790: New client connected from 10.0.2.2 as sub (c0, k60).
1530684790: No will message specified.
1530684790: Sending CONNACK to sub (0, 0)
1530684790: Saving in-memory database to /home/ckrey/mosquitto/mosquitto.db.
1530684790: Received SUBSCRIBE from sub
1530684790: 	topic (QoS 1)
1530684790: sub 1 topic
1530684790: Sending SUBACK to sub
1530684790: Saving in-memory database to /home/ckrey/mosquitto/mosquitto.db.
1530684797: New connection from 10.0.2.2 on port 1883.
1530684797: New client connected from 10.0.2.2 as pub (c1, k60).
1530684797: No will message specified.
1530684797: Sending CONNACK to pub (0, 0)
1530684797: Received PUBLISH from pub (d0, q1, r0, m1, 'topic', ... (5 bytes))
1530684797: Sending PUBACK to pub (Mid: 1)
1530684797: Saving in-memory database to /home/ckrey/mosquitto/mosquitto.db.
1530684797: Received DISCONNECT from pub
1530684797: Client pub disconnected.
```

```
$ mosquitto/src/db_dump/mosquitto_db_dump --client-stats  mosquitto.db
SC: 0 SS: 0 MC: 0 MS: 0   sub
```

**Comment by toast-uz** [comment] 2018-07-17 13:02
I reproduced @sxsing 's issue on v1.5 although not on v1.4.15.

**Comment by toast-uz** [comment] 2018-07-17 13:48
I identified the first bad commit by using git_bisect.

```
5ff8127f44de57aebaccbe7e0b85a80d2c48fa2e is the first bad commit
commit 5ff8127f44de57aebaccbe7e0b85a80d2c48fa2e
Author: Roger A. Light <roger@atchoo.org>
Date:   Wed Apr 11 23:17:17 2018 +0100

    Fix will sending for duplicate clients.
    
    When a client with an in-use client-id connects, if the old client has a
    will, send the will message. Closes #26.
    
    Thanks to Pierre F.

:100644 100644 622eaf3324b9ab02c49211d722a881e4a622e5bb 2ed754ea34f588c623ca7b90bd86a3aa9cbe1557 M	ChangeLog.txt
:040000 040000 f0e65a8acc71fa745dcf60e8ef2ea5d620a60671 90c35ae41cece3d92eb4b17937385b3871eeca8f M	src
```

**Comment by toast-uz** [comment] 2018-07-17 14:02
I confirmed this issue has resolved on v1.5 with undoing the bad commit. Although I could not find what should do.

**Comment by dmiller-tibco** [comment] 2018-07-19 13:20
Thanks toast-uz for the info.  

With this information, sxsing and I are testing a possible fix that continues to fix the #26 will problem, without creating subscription problems for the new clean session.  Should be able to finish testing in the next day or two.

**Comment by ralight** [comment] 2018-08-01 18:40
The PR fixing this has now been merged, and I've added a test for it as well. If you could give the fixes branch a try and comment here, then we can close the issue.

**Comment by sxsing** [comment] 2018-08-01 21:40
The new test has passed.

make WITH_TLS=no WITH_UUID=no WITH_DOCS=no test
......
./02-subscribe-qos0.py
./02-subscribe-qos1.py
./02-subscribe-qos2.py
./02-subpub-qos0.py
./02-subpub-qos1.py
./02-subpub-qos2.py
./02-unsubscribe-qos0.py
./02-unsubscribe-qos1.py
./02-unsubscribe-qos2.py
./02-unsubscribe-invalid-no-topic.py
./02-subscribe-invalid-utf8.py
./02-subscribe-persistence-flipflop.py
./03-publish-qos1.py
./03-publish-qos2.py
./03-publish-b2c-disconnect-qos1.py
./03-publish-c2b-disconnect-qos2.py
./03-publish-b2c-disconnect-qos2.py
......

**Comment by ralight** [comment] 2018-08-01 23:39
Thanks for checking - did you also run your own manual test to be sure I got the test right? :)

**Comment by sxsing** [comment] 2018-08-02 16:04
I tested manually using commands at the beginning of this issue. Nothing wrong this time.

**Comment by ralight** [comment] 2018-08-14 16:17
Great, thanks for the feedback I'm closing the issue.

**Closed by ralight** 2018-08-14 16:17 UTC
Labels: bug, mosquitto-broker, pending-close
