### ISSUE TITLE
mosquitto plugin and clientid

### ISSUE THREAD

**Issue by bjornwennberg71** [eclipse/mosquitto#878] opened 2018-07-05 11:28 UTC
I would like to know the connected client-id upon the first entry into
mosquitto_auth_unpwd_check
so that I can store a remote id-token upon later call to the auth_acl call.

As I can read from the source, the context->id should be a unique client_id per connection, but it is not set until after the auth_unpwd_check is performed.

**Comment by toast-uz** [comment] 2018-07-14 05:41
I think the current implementation avoids determination client-id before validation of username in order to consider about conf directive: ```use_username_as_clientid```.

**Comment by toast-uz** [comment] 2018-07-19 12:52
Closing because this seems not a bug.
Please reopen and change the subject If you insist on reporting a bug. This place is not for a question nor for a new feature's request. Look at the instruction (https://mosquitto.org/).

**Closed by toast-uz** 2018-07-19 12:52 UTC
Labels: enhancement, not a bug
