### ISSUE TITLE
QoS 0 messages shouldn't be persisted unless queue_qos0_messages is true

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#192] opened 2016-06-21 16:22 UTC

**Comment by Aeefire** [comment] 2017-01-11 07:58
I have the following issue: When I disconnect a subscriber which received qos0 messages before while the publisher keeps publishing and then reconnect the subscriber, it will receive both the messages which were published while disconnected, as well as the new messages in an alternating pattern (old-new-old-new-old-new...). Is this caused by this issue? Will we see a fix for this anytime soon? Or do you have an idea where the issue lies, so I could try to get my own hands on it.

**Closed** 2021-01-09 09:56 UTC
Labels: bug, mosquitto-broker
