### ISSUE TITLE
crash!!!

### ISSUE THREAD

**Issue by fog1111** [eclipse/mosquitto#633] opened 2017-11-30 11:07 UTC
mosquitto: loop.c:488: loop_handle_reads_writes: Assertion `pollfds[context->pollfd_index].fd == context->sock' failed.

**Comment by karlp** [comment] 2017-11-30 11:11
Do you have any useful context for this?  Without even basic information like the mosquitto version you're using, it's pretty hard to do anything meaningful with a ticket like this.

**Comment by fog1111** [comment] 2017-11-30 12:32
mosquitto version:1.4.14
os:centos 7
this issue happend several times, i don't  catch some useful information.
maybe this issue  is related to websocket

**Comment by toast-uz** [comment] 2017-11-30 13:01
Could you show your mosquitto.conf and a reproduce procedure?

**Comment by fog1111** [comment] 2017-12-01 02:06
mosquitto.conf:
# Port to use for the default listener.
port 1883
listener 9001
protocol websockets

i build mosquitto in centos and run it

**Comment by toast-uz** [comment] 2017-12-01 10:08
I didn't encounter an issue by your conf.

Could you add followings at the bottom of your conf?

```
log_type all
websockets_log_level 255
```

And report mosquitto log if you can reproduce the issue.

My log (no problem) was followings:
```
1512122469: mosquitto version 1.4.14 (build date 2017-12-01 10:00:38+0000) starting
1512122469: Config loaded from websockets_test.conf.
1512122469: Opening websockets listen socket on port 9001.
1512122469: Initial logging level 255
1512122469: Libwebsockets version: 2.3.0 centos@ip-172-31-17-231.ap-northeast-1.compute.internal-v2.0.0-487-g07b444c
1512122469: IPV6 not compiled in
1512122469: libev support not compiled in
1512122469: libuv support not compiled in
1512122469:  Threads: 1 each 240000 fds
1512122469:  mem: platform fd map: 1920000 bytes
1512122469:  Compiled with OpenSSL support
1512122469: Doing SSL library init
1512122469: Creating Vhost 'default' port 9001, 3 protocols, IPv6 off
1512122469:  Using non-SSL mode
1512122469:  Listening on port 9001
1512122469:  mem: per-conn:          584 bytes + protocol rx buf
1512122469:  canonical_hostname = ip-172-31-17-231.ap-northeast-1.compute.internal
1512122469: Opening ipv4 listen socket on port 1883.
1512122469: Opening ipv6 listen socket on port 1883.
```

**Comment by szymonskirgajllo** [comment] 2018-02-13 18:09
@toast-uz @karlp hi

i think that this issue is related with mosquitto-auth-plug

i have:
- mosquitto 1.4.14
- libwebsockets 2.4.1
- mosquitto-auth-plugin https://github.com/jpmens/mosquitto-auth-plug (i am using jwt backend)
- Operating System: CentOS Linux 7 (Core) => centos-release-7-4.1708.el7.centos.x86_64

when i run mosquitto, everything looks ok...
```
/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
1518532919: mosquitto version 1.4.14 (build date 2018-02-08 13:24:11+0000) starting
1518532919: Config loaded from /etc/mosquitto/mosquitto.conf.
1518532919: |-- *** auth-plug: startup
1518532919: |-- ** Configured order: jwt

1518532919: |-- with_tls=false
1518532919: |-- getuser_uri=/getuser
1518532919: |-- superuser_uri=/superuser
1518532919: |-- aclcheck_uri=/aclcheck
1518532919: |-- getuser_params=(null)
1518532919: |-- superuser_params=(null)
1518532919: |-- aclcheck_paramsi=(null)
1518543602: Opening ipv4 listen socket on port 1883.
1518543602: Opening websockets listen socket on port 9001
```

but after a few seconds process fails with
```
mosquitto: loop.c:488: loop_handle_reads_writes: Assertion `pollfds[context->pollfd_index].fd == context->sock' failed.
```

full log
```
/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
1518543722: mosquitto version 1.4.14 (build date 2018-02-08 13:24:11+0000) starting
1518543722: Config loaded from /etc/mosquitto/mosquitto.conf.
1518543722: |-- *** auth-plug: startup
1518543722: |-- ** Configured order: jwt

1518543722: |-- with_tls=false
1518543722: |-- getuser_uri=/getuser
1518543722: |-- superuser_uri=/superuser
1518543722: |-- aclcheck_uri=/aclcheck
1518543722: |-- getuser_params=(null)
1518543722: |-- superuser_params=(null)
1518543722: |-- aclcheck_paramsi=(null)
1518543722: Opening ipv4 listen socket on port 1883.
1518543722: Opening websockets listen socket on port 9001.
1518543722: New connection from 192.168.11.82 on port 1883.
1518543722: |-- mosquitto_auth_unpwd_check(super_username)
1518543722: |-- ** checking backend jwt
1518543722: |-- url=http://example.com:80/getuser
1518543722: |-- data=topic=&acc=-1&clientid=
1518543722: |-- getuser(super_username) AUTHENTICATED=1 by jwt
1518543722: New client connected from 192.168.11.82 as mqttjs_3d5883b6 (c1, k60, u'super_username').
1518543722: New connection from 192.168.11.82 on port 1883.
1518543722: |-- mosquitto_auth_unpwd_check(super_username)
1518543722: |-- ** checking backend jwt
1518543722: |-- url=http://example.com:80/getuser
1518543722: |-- data=topic=&acc=-1&clientid=
1518543722: |-- getuser(super_username) AUTHENTICATED=1 by jwt
1518543722: New client connected from 192.168.11.82 as mqttjs_fb7c5daa (c1, k60, u'super_username').
1518543723: |-- mosquitto_auth_unpwd_check(super_username)
1518543723: |-- ** checking backend jwt
1518543723: |-- url=http://example.com:80/getuser
1518543723: |-- data=topic=&acc=-1&clientid=
1518543723: |-- getuser(super_username) AUTHENTICATED=1 by jwt
1518543723: New client connected from 192.168.27.38 as mqttjs_60a5d7ea (c1, k60, u'super_username').
1518543726: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543726: |-- ** checking backend jwt
1518543726: |-- url=http://example.com:80/getuser
1518543726: |-- data=topic=&acc=-1&clientid=
1518543727: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543727: |-- mosquitto_auth_unpwd_check(add63456e6e7a8e2d622acb3af4f706c87feaa76)
1518543727: |-- ** checking backend jwt
1518543727: |-- url=http://example.com:80/getuser
1518543727: |-- data=topic=&acc=-1&clientid=
1518543727: |-- getuser(add63456e6e7a8e2d622acb3af4f706c87feaa76) AUTHENTICATED=0 by none
1518543728: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543728: |-- ** checking backend jwt
1518543728: |-- url=http://example.com:80/getuser
1518543728: |-- data=topic=&acc=-1&clientid=
1518543728: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543730: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543730: |-- ** checking backend jwt
1518543730: |-- url=http://example.com:80/getuser
1518543730: |-- data=topic=&acc=-1&clientid=
1518543730: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543731: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543731: |-- ** checking backend jwt
1518543731: |-- url=http://example.com:80/getuser
1518543731: |-- data=topic=&acc=-1&clientid=
1518543731: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543731: |-- mosquitto_auth_unpwd_check(add63456e6e7a8e2d622acb3af4f706c87feaa76)
1518543731: |-- ** checking backend jwt
1518543731: |-- url=http://example.com:80/getuser
1518543731: |-- data=topic=&acc=-1&clientid=
1518543731: |-- getuser(add63456e6e7a8e2d622acb3af4f706c87feaa76) AUTHENTICATED=0 by none
1518543731: Socket error on client <unknown>, disconnecting.
1518543732: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543732: |-- ** checking backend jwt
1518543732: |-- url=http://example.com:80/getuser
1518543732: |-- data=topic=&acc=-1&clientid=
1518543732: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543733: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543733: |-- ** checking backend jwt
1518543733: |-- url=http://example.com:80/getuser
1518543733: |-- data=topic=&acc=-1&clientid=
{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unaut1518543733: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543733: Socket error on client <unknown>, disconnecting.
1518543735: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543735: |-- ** checking backend jwt
1518543735: |-- url=http://example.com:80/getuser
1518543735: |-- data=topic=&acc=-1&clientid=
1518543735: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543735: Socket error on client <unknown>, disconnecting.
1518543735: |-- mosquitto_auth_unpwd_check(add63456e6e7a8e2d622acb3af4f706c87feaa76)
1518543735: |-- ** checking backend jwt
1518543735: |-- url=http://example.com:80/getuser
1518543735: |-- data=topic=&acc=-1&clientid=
1518543735: |-- getuser(add63456e6e7a8e2d622acb3af4f706c87feaa76) AUTHENTICATED=0 by none
1518543736: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543736: |-- ** checking backend jwt
1518543736: |-- url=http://example.com:80/getuser
1518543736: |-- data=topic=&acc=-1&clientid=
1518543736: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543737: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543737: |-- ** checking backend jwt
1518543737: |-- url=http://example.com:80/getuser
1518543737: |-- data=topic=&acc=-1&clientid=
1518543737: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543738: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543738: |-- ** checking backend jwt
1518543738: |-- url=http://example.com:80/getuser
1518543738: |-- data=topic=&acc=-1&clientid=
1518543738: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543739: |-- mosquitto_auth_unpwd_check(add63456e6e7a8e2d622acb3af4f706c87feaa76)
1518543739: |-- ** checking backend jwt
1518543739: |-- url=http://example.com:80/getuser
1518543739: |-- data=topic=&acc=-1&clientid=
1518543739: |-- getuser(add63456e6e7a8e2d622acb3af4f706c87feaa76) AUTHENTICATED=0 by none
1518543740: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543740: |-- ** checking backend jwt
1518543740: |-- url=http://example.com:80/getuser
1518543740: |-- data=topic=&acc=-1&clientid=
1518543740: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543741: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543741: |-- ** checking backend jwt
1518543741: |-- url=http://example.com:80/getuser
1518543741: |-- data=topic=&acc=-1&clientid=
horized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.1518543741: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543742: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543742: |-- ** checking backend jwt
1518543742: |-- url=http://example.com:80/getuser
1518543742: |-- data=topic=&acc=-1&clientid=
1518543742: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543743: |-- mosquitto_auth_unpwd_check(add63456e6e7a8e2d622acb3af4f706c87feaa76)
1518543743: |-- ** checking backend jwt
1518543743: |-- url=http://example.com:80/getuser
1518543743: |-- data=topic=&acc=-1&clientid=
1518543743: |-- getuser(add63456e6e7a8e2d622acb3af4f706c87feaa76) AUTHENTICATED=0 by none
1518543743: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543743: |-- ** checking backend jwt
1518543743: |-- url=http://example.com:80/getuser
1518543743: |-- data=topic=&acc=-1&clientid=
1518543743: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543745: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543745: |-- ** checking backend jwt
1518543745: |-- url=http://example.com:80/getuser
1518543745: |-- data=topic=&acc=-1&clientid=
1518543745: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543746: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543746: |-- ** checking backend jwt
1518543746: |-- url=http://example.com:80/getuser
1518543746: |-- data=topic=&acc=-1&clientid=
1518543746: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543747: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543747: |-- ** checking backend jwt
1518543747: |-- url=http://example.com:80/getuser
1518543747: |-- data=topic=&acc=-1&clientid=
1518543747: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543747: |-- mosquitto_auth_unpwd_check(add63456e6e7a8e2d622acb3af4f706c87feaa76)
1518543747: |-- ** checking backend jwt
1518543747: |-- url=http://example.com:80/getuser
1518543747: |-- data=topic=&acc=-1&clientid=
org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"1518543747: |-- getuser(add63456e6e7a8e2d622acb3af4f706c87feaa76) AUTHENTICATED=0 by none
1518543748: Socket error on client <unknown>, disconnecting.
1518543748: Socket error on client <unknown>, disconnecting.
1518543748: Socket error on client mqttjs_60a5d7ea, disconnecting.
1518543748: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543748: |-- ** checking backend jwt
1518543748: |-- url=http://example.com:80/getuser
1518543748: |-- data=topic=&acc=-1&clientid=
1518543748: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543749: Socket error on client <unknown>, disconnecting.
1518543749: |-- mosquitto_auth_unpwd_check(super_username)
1518543749: |-- ** checking backend jwt
1518543749: |-- url=http://example.com:80/getuser
1518543749: |-- data=topic=&acc=-1&clientid=
1518543749: |-- getuser(super_username) AUTHENTICATED=1 by jwt
1518543749: New client connected from 192.168.27.38 as mqttjs_44cc5606 (c1, k60, u'super_username').
1518543750: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543750: |-- ** checking backend jwt
1518543750: |-- url=http://example.com:80/getuser
1518543750: |-- data=topic=&acc=-1&clientid=
1518543750: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
1518543751: Socket error on client <unknown>, disconnecting.
1518543751: |-- mosquitto_auth_unpwd_check(b26c9ac0a79d12fda710ea1c28b37ff20d76d648)
1518543751: |-- ** checking backend jwt
1518543751: |-- url=http://example.com:80/getuser
1518543751: |-- data=topic=&acc=-1&clientid=
1518543751: |-- getuser(b26c9ac0a79d12fda710ea1c28b37ff20d76d648) AUTHENTICATED=0 by none
mosquitto: loop.c:488: loop_handle_reads_writes: Assertion `pollfds[context->pollfd_index].fd == context->sock' failed.
detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"User is not authorized"}Aborted

```

i think that neccessary information is that my backend usually returns response with 4xx code

when I changed my backend so that it would always return 2xx, then mosquitto works fine
```
1518544347: |-- mosquitto_auth_unpwd_check(073dddcf0eb9aa49ddc8f4a106cc8012ba9ccbb2)
1518544347: |-- ** checking backend jwt
1518544347: |-- url=http://example.com:80/getuser
1518544347: |-- data=topic=&acc=-1&clientid=
1518544347: |-- getuser(073dddcf0eb9aa49ddc8f4a106cc8012ba9ccbb2) AUTHENTICATED=1 by jwt
1518544347: New client connected from 192.168.11.82 as mqttjs_5f293225 (c1, k60, u'073dddcf0eb9aa49ddc8f4a106cc8012ba9ccbb2').
```

**Comment by toast-uz** [comment] 2018-02-14 21:19
I didn't find the evidence of using auth-plug on your mosquitto.conf on 1 Dec 2017.
Will you report the issue to https://github.com/jpmens/mosquitto-auth-plug ?

**Comment by szymonskirgajllo** [comment] 2018-02-15 08:20
@toast-uz i will try, thanks for the reply

**Comment by szymonskirgajllo** [comment] 2018-03-01 08:44
@toast-uz this problem is still actual 

https://github.com/szymonskirgajllo/mosquitto-1.4.14-crash

i've created repository with docker container for mosquitto and scripts in javascript (mqtt client) which crash mosquitto after a few seconds or minutes

in this repository you have steps to reproduce this problem

i would like to ask you about debug and fix this problem ;)

**Comment by toast-uz** [comment] 2018-03-02 13:04
@szymonskirgajllo , I didn't know your environment is with docker. Could you simplify your environment and reproducing procedure? 

Further more, I'd like to reconfirm that you found your issue was depend on mosquitto-auth-plug. If so, this is not the right place. You should report to https://github.com/jpmens/mosquitto-auth-plug .

**Comment by szymonskirgajllo** [comment] 2018-03-09 14:21
@toast-uz ok, i found it :) my problem is not related with mosquitto-auth-plugin

i've pushed mosquitto without auth plugin to my repository ("wihtout_auth_plugin" branch)
https://github.com/szymonskirgajllo/mosquitto-1.4.14-crash/tree/wihtout_auth_plugin

please check it, read instruction in readme (there is reproducing procedure), run this docker-compose and fix this problem ;)

environment is docker, but i had the same problem on centos7 with mosquitto 1.4.14
mosquitto has enabled websockets

**Comment by toast-uz** [comment] 2018-03-09 14:35
@szymonskirgajllo could you reproduce the issue without docker? Simplify the environment is very important to clarify the cause.

**Comment by ralight** [comment] 2018-03-09 23:02
@szymonskirgajllo I've followed your procedure, but have had to use mosquitto=1.4.15-r0 instead. It has been running a long while now with no problems. Could you please try again yourself?

**Comment by szymonskirgajllo** [comment] 2018-03-14 13:10
@ralight yeah :D it works well with 1.4.15 ;)

i think that this issue can be closed ;)

**Comment by toast-uz** [comment] 2018-03-14 14:00
This issue was produced by @fog1111 .
Closing as no more information from @fog1111 for a few months.

**Closed by toast-uz** 2018-03-14 14:00 UTC
Labels: need-more-information
