### ISSUE TITLE
Mosquitto inflight_messages = 1, but got more than 1 message simultaneously

### ISSUE THREAD

**Issue by Asoul** [eclipse/mosquitto#393] opened 2017-03-07 03:59 UTC
I've set `max_inflight_messages` to 1, but after stress test, my client got multiple simultaneous messages.

Does I misunderstood something? I thought `in-order delivery of messages` means every message should sent through PUBLISH, PUBREC, PUBREL, PUBCOMP, then next message.

Extracted `mosquitto.log`
```
1488858217: Sending PUBLISH to client (d0, q2, r0, m669, 'test/topic', ... (7 bytes))
1488858217: Sending PUBLISH to client (d0, q1, r0, m670, 'test/topic', ... (7 bytes))
1488858217: Sending PUBLISH to client (d0, q2, r0, m671, 'test/topic', ... (7 bytes))
1488858217: Sending PUBLISH to client (d0, q2, r0, m672, 'test/topic', ... (7 bytes))
1488858217: Sending PUBLISH to client (d0, q2, r0, m673, 'test/topic', ... (7 bytes))
1488858217: Received PUBREC from client (Mid: 669)
1488858217: Sending PUBREL to client (Mid: 669)
1488858217: Received PUBACK from client (Mid: 670)
1488858217: Received PUBREC from client (Mid: 671)
1488858217: Sending PUBREL to client (Mid: 671)
1488858217: Received PUBREC from client (Mid: 672)
1488858217: Sending PUBREL to client (Mid: 672)
1488858217: Received PUBREC from client (Mid: 673)
1488858217: Sending PUBREL to client (Mid: 673)
```

Thanks,
Asoul

**Comment by ThomasKrannich** [comment] 2017-07-05 13:59
Same behavior and question here. (Broker is Mosquitto and Subscriber is paho (Java))
QoS is 2 and the above behavior leads to messages getting lost - as it seems because retry_interval is reached before the first published message was confirmed with PUBREC.

**Comment by asicoe** [comment] 2017-08-19 10:46
I am seeing the same behaviour as Asoul.
My test is not even a stress test
I have a mosquitto broker and a publisher and a subscriber client. Both using java paho 1.1.1.
I publish some messages to one topic, then let the consumer consume for a while. Then shutdown the consumer (which has a persistent session). During the downtime some more messages are published. When the consumer is brought back mosquitto publishes multiple messages together exactly in the pattern that Asoul pasted. So we end up with multiple msgs in flight which leads to out of order messages in our app. This happens with Mosquitto 1.4.12 and max_inflight_messages = 1.

This behavior does not happen with HiveMQ for the exact same test.

**Comment by tonydicamillo** [comment] 2017-09-28 18:11
I am seeing this same issue using Mosquitto 1.4.14, max_inflight_messages = 1. The broker sends multiple PUBLISH to my client before my client can PUBREC the first one. 

This is a major issue for me since this behavior is different from the previous version we were using (1.3.5)

**Comment by toast-uz** [comment] 2017-10-01 08:07
This issue was fixed on latest develop branch, while not fixed on master branch of even 1.4.14.
Attention the log message 'Sending' is an advance announcement of sending message, it is not guaranteed simultaneously with actual packets transferring.

I made a test of this issue. Please reconfirm this test passes on develop and fails on master.
You can watch the actual packets transferring with deleting # of line 34 in 03-publish-qos2-inflight.py.

**Comment by tonydicamillo** [comment] 2017-11-02 14:22
This probably isn't the right place to ask this... do you know when this fix will become available in the main branch? Is there a planned release date for 1.4.15?

**Comment by toast-uz** [comment] 2017-11-04 00:52
Thank you for your endorsement.
Could you close this issue? You can write messages on #473 when you want to remind the committer of this request.

**Comment by toast-uz** [comment] 2018-03-02 14:12
Closing because solved the original issue on develop.

**Closed by toast-uz** 2018-03-02 14:12 UTC

**Comment by tacooper** [comment] 2018-03-02 14:18
Just to be clear, is this fix included in the recent 1.4.15 release?

**Comment by toast-uz** [comment] 2018-03-02 14:30
Current develop branch will be released on the next major version v.1.5, soon.

**Comment by gwainer** [comment] 2018-05-07 11:59
Any idea when this will happen?

**Comment by tacooper** [comment] 2018-05-29 14:12
@toast-uz it looks like v1.5 is released, but any idea on when the Windows executable will be available for download? thanks

**Comment by gwainer** [comment] 2018-05-29 21:04
@tacooper I'm on a mac, but inside the download package at http://mosquitto.org/files/source/mosquitto-1.5.tar.gz in the installer folder there's mosquitto.nsi and mosquitto64.nsi, maybe a windows installer...

**Comment by tacooper** [comment] 2018-05-31 12:27
@gwainer 
I wouldn't solely go by that list, but hopefully @ralight or @toast-uz can confirm that the fix in `develop` branch was included.
