### ISSUE TITLE
Subscribe with QoS=0 and packet identifier 0 incorrectly rejected

### ISSUE THREAD

**Issue by tve** [eclipse/mosquitto#2572] opened 2022-06-17 17:24 UTC
Mosquitto 2.0.14 rejects a subscribe command that has QoS=0 and Packet Identifier = 0. Looking at section 2.3.1 of the mqtt 3.1.1 spec (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html) it says:

> SUBSCRIBE, UNSUBSCRIBE, and PUBLISH (in cases where QoS > 0) Control Packets MUST contain a non-zero 16-bit Packet Identifier [MQTT-2.3.1-1].

Notice the "in cases where QoS > 0". Apologies if I'm missing some other part of the spec that states that packet ID of 0 is always invalid (I have old clients that use it and that have worked fine for years with mosquitto pre-V2).

Reproduction. The first command shows the failure, the second one shows a successful subscription. The only difference is a packet id of 0 vs. 1 in the subscribe command.
```
> echo -en '\x10\x21\x00\x04MQTT\x04\x00\x00\x00\x00\x15HEATMAT-deaddead-1234\x82\x12\x00\x00\x00\x0dsystem/offset\x00' | nc -q 2 ncore 1883 | od -x
0000000 0220 0001
0000004
> echo -en '\x10\x21\x00\x04MQTT\x04\x00\x00\x00\x00\x15HEATMAT-deaddead-1234\x82\x12\x00\x01\x00\x0dsystem/offset\x00' | nc -q 2 ncore 1883 | od -x
0000000 0220 0001 0390 0100 0000
0000011
```
The first example results in an error in the mosquitto log of "Client HEATMAT-deaddead-1234 disconnected due to malformed packet."

Mosquitto 2.0.14 on Manjaro Linux

**Comment by Lorenzooone** [comment] 2022-06-27 00:23
Reproduced it on Windows (albeit not voluntarily).
My devices were not subscribing to the topics, but my python code was. Went to look at it with wireshark and yup... It's the ID.

**Comment by ralight** [comment] 2022-08-07 07:35
I'm afraid this is working exactly as expected. To clarify the spec, it is saying

SUBSCRIBE must have a non zero packet id (SUBSCRIBE is treated as a QoS 1 type message which requires a reply)
UNSUBSCRIBE must have a non zero packet id (UNSUBSCRIBE is treated as a QoS 1 type message which requires a reply)
PUBLISH must have a non zero packet id, if the PUBLISH is being sent with QoS > 0. A PUBLISH with QoS = 0 does not have a packet id at all.

Prior to this change, Mosquitto was not compliant with the spec, and now it is. This has the side effect of exposing situations where other clients are not compliant either which is frustrating for you.

**Comment by ralight** [comment] 2022-08-07 22:23
I'm closing this issue because I think I've addressed it sufficiently to answer what you need. I'm trying to close issues like this to get on top of the issues list. If there is still something left to do on this issue, please reopen it and give more details.

**Closed by ralight** 2022-08-07 22:23 UTC
