### ISSUE TITLE
Error while starting mosquitto broker with protocol websockets (docker-container)

### ISSUE THREAD

**Issue by MerzMax** [eclipse/mosquitto#2308] opened 2021-09-10 08:30 UTC
I use the mosquitto docker container version **2.0.12**.

I can't start the broker with the option "protocol websockets" anymore. This is the output of my container: 

```bash
mqtt_broker_1  | 1631261934: Error: Invalid protocol value (websockets
mqtt_broker_1  | 1631261934: Error found at /mosquitto/config/mosquitto.conf:2.
mqtt_broker_1 exited with code 0
```

My mosquitto.conf:
```conf
listener 9001
protocol websockets

allow_anonymous true
log_type all
```

**Comment by T81** [comment] 2021-09-21 12:10
Same issue here

**Comment by ralight** [comment] 2021-09-22 09:06
I've just tested this out as below, and it worked fine. Can you give any hints as to what is different in your situation? Or try it exactly as I did?

![2308](https://user-images.githubusercontent.com/79578/134315219-b6ea6b61-0ca2-4c77-891e-d77ddda0d7e8.png)

**Comment by MerzMax** [comment] 2021-09-22 11:00
@ralight If i ececute the the same command, I get the following output:
```bash 
$ more Mosquitto/mosquitto.conf 
listener 9001
protocol websockets

allow_anonymous true
log_type all
$ docker run -it -p 9001:9001 -v ${PWD}/Mosquitto:/mosquitto/config eclipse-mosquitto:2.0.12
Unable to find image 'eclipse-mosquitto:2.0.12' locally
2.0.12: Pulling from library/eclipse-mosquitto
a0d0a0d46f8b: Pull complete
0923389132a8: Pull complete
Digest: sha256:ce08d3fe69d4170cea2426739af86ac95e683f01dd2c4141da661983a2401364
Status: Downloaded newer image for eclipse-mosquitto:2.0.12
).32308106: Error: Invalid protocol value (websockets
1632308106: Error found at /mosquitto/config/mosquitto.conf:2.
```

**Comment by ralight** [comment] 2021-09-22 11:30
@MerzMax Hmm, very interesting. What platform are you running Docker on?

**Comment by MerzMax** [comment] 2021-09-22 12:27
@ralight Windows with wsl 2.

**Comment by ralight** [comment] 2021-09-22 12:52
Thanks, I'll get myself set up with Docker on WSL 2 and give it a try, it might not be straight away.

**Comment by ralight** [comment] 2021-09-22 19:55
This looks to be a duplicate of #2297, I'm going to close this and track it there if that's ok.

**Closed by ralight** 2021-09-22 19:55 UTC
