### ISSUE TITLE
Make fails on Raspbian Jessie in read_handle_server.o

### ISSUE THREAD

**Issue by moyerai** [eclipse/mosquitto#153] opened 2016-05-11 19:45 UTC
Making Mosquitto (v. 1.4.8) fails when building read_handle_server.o with an invalid pointer dereference:

make[1]: Entering directory '/home/pi/src/mosquitto/src'
cc -Wall -ggdb -O2  -I. -I.. -I../lib  -DVERSION="\"1.4.8\"" -DTIMESTAMP="\"2016-05-11 19:36:29+0000\"" -DWITH_BROKER -DWITH_TLS -DWITH_TLS_PSK -DWITH_UUID -DWITH_BRIDGE -DWITH_PERSISTENCE -DWITH_MEMORY_TRACKING -DWITH_SYS_TREE -DWITH_EC -c read_handle_server.c -o read_handle_server.o
read_handle_server.c: In function ‘mqtt3_handle_connect’:
read_handle_server.c:367:77: error: dereferencing pointer to incomplete type
    context->username = _mosquitto_strdup((char *)ASN1_STRING_data(name_entry->value));
                                                                             ^
Makefile:54: recipe for target 'read_handle_server.o' failed
make[1]: *** [read_handle_server.o] Error 1
make[1]: Leaving directory '/home/pi/src/mosquitto/src'
Makefile:21: recipe for target 'mosquitto' failed
make: *** [mosquitto] Error 2

System: Raspberry Pi 3 running Rasbian Jessie, uname output is: Linux bettencourt 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux

Output from lsb_release -a is:
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

If there is other information you need, just let me know!

**Comment by ralight** [comment] 2016-05-11 19:49
What version of openssl is this? `apt-cache policy openssl` would tell you.

**Comment by moyerai** [comment] 2016-05-11 19:58
openssl:
  Installed: 1.0.1k-3+deb8u5
  Candidate: 1.0.1k-3+deb8u5
  Version table:
 *** 1.0.1k-3+deb8u5 0
        500 http://mirrordirector.raspbian.org/raspbian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status

But I also compiled and installed the most recent version from github (as of this morning). It is in /usr/local, which means it is in the path before the apt version.

**Comment by ralight** [comment] 2016-05-11 20:05
Oh right, that'll be it then. I imagine the latest version is what will become 1.1.0, which includes a big tidy up of what were notionally private data structures but weren't in practice. That's something for me to fix in the future.

**Comment by ralight** [comment] 2016-05-15 19:54
I'm closing this for the moment because it's not a bug at the moment.

**Closed by ralight** 2016-05-15 19:54 UTC
