### ISSUE TITLE
with QoS 2 libmosquitto fails to deliver properties to msg callback

### ISSUE THREAD

**Issue by bschaer** [eclipse/mosquitto#1436] opened 2019-09-30 08:41 UTC
If an application using libmosquitto gets a message which has been delivered with QoS 2, then all properties are not delivered to the callback method which has been registered with `mosquitto_publish_v5_callback_set()`.
The reason for that lies in file `handle_publish.c`, line 159: In case of QoS 2 messages, the message is not delivered right away, but put into a delivery queue with the method `message__queue`. Since this queue doesn't seem to support properties, they got dropped at this place and can no longer delivered to the application code.

**Comment by karlp** [comment] 2019-09-30 10:25
duplicate of https://github.com/eclipse/mosquitto/issues/1432

**Closed** 2019-09-30 10:35 UTC
