### ISSUE TITLE
Broker hangs when it is sending data OUT to bridged broker

### ISSUE THREAD

**Issue by catan85** [eclipse/mosquitto#174] opened 2016-05-27 11:34 UTC
I see that when connection is lost and I have a lot of data in my mosquitto.db, when the connection to the bridge comes back the broker become unresponsive untill it finishes to send data to the bridge.

**Comment by ralight** [comment] 2016-05-30 20:53
Could you give a few details of what the bridge config looks like and how much "a lot of data" is to make debugging easier?

**Comment by catan85** [comment] 2016-05-30 21:12
Sure, for lot of data I mean something like 400-500 mb.
More are the data and the easier you can reproduce the problem.
During the message sending to the bridged broker the clients times out (it can take minutes, or hours)

The pricipal configurations are the following:
`
autosave_interval 60
max_queued_messages 3000000
persistence true
persistence_file mosquitto.db
queue_qos0_messages true

connection azure
address xxx.azure-devices.net:8883
cleansession false
start_type automatic
clientid xxx
remote_username xxx.azure-devices.net/xxx
remote_password SharedAccessSignature sr=foobar.azure-devices.net%2fdevices%2ftest&sig=CHANGEME2bN06SOMEMORECHARS%2bsA%3d&se=123456789
bridge_insecure false
bridge_protocol_version mqttv311
bridge_capath /etc/ssl/certs
bridge_tls_version tlsv1
notifications false
try_private false
topic # out 0 devices/test/messages/events/ devices/test/messages/events/
log_dest stdout
log_type debug
`
I need that huge msg quantity because the internet connection can go down for days.

**Comment by PierreF** [comment] 2018-01-02 10:25
I think your issue is #172: while writing persistence database mosquitto stop its processing.
The solution are:
* faster disk
* turn down queue sizes
* increase autosave (mosquitto will still hang but less often).

I don't reproduce unresponsiveness with large database (in my test 400 Mb with 3M messages). I only see:
* larger "ping" time (sent MQTT message with timestamp, on receiving compute delay): while busy, ping is ~20ms instead of 1ms
* unqueing is slow (in my case ~3600 msgs/minutes): #140/#141

Both larger "ping" and slow unqueue are fixed in develop ("ping" stay are ~1ms, unqueue go up to 2M msgs/minutes).

Closing as duplicate of other issues.

**Closed by PierreF** 2018-01-02 10:25 UTC
