### ISSUE TITLE
not able to send continuous data to mosquitto

### ISSUE THREAD

**Issue by zeref-dragneel** [eclipse/mosquitto#972] opened 2018-09-25 12:51 UTC
I am trying to send from Raspberry pi to mosquitto installed on a windows pc, i am trying to send 5 data, but the mosquitto seems to get only one data

coding for raspberry pi

```
from datetime import datetime
import paho.mqtt.client as mqtt
#connecting to broker
client=mqtt.Client()
client.connect("192.168.0.104",1883,60)
#posting data to broker
for i in range(0,5):
    dt=str(datetime.now())
    json_data={'dt':dt,'1':'a'}
    client.publish("/test",str(json_data))
    print(json_data)
```
program to read data at broker
```
import simplejson as json
import paho.mqtt.client as mqtt
import simplejson as json

print("attempting to connect...")

def on_connect(client, userdata, flags, rc):
  if(rc==0):
    print("connection successful broker linked")
  elif(rc==1):
    print("connection refused -  incorrect protocol version")
  elif(rc==2):
    print("connection refused - invalid client identifier")
  elif(rc==3):
    print("connection refused- server unavailable")
  elif(rc==4):
    print("connection refused- bad username or password")
  elif(rc==5):
    print("connection refused- not authorised")
  else:
    print("currently unused")
    
  client.subscribe("/test")
def on_message(client, userdata, msg):
    data=eval(msg.payload)
    print(data)
    
client = mqtt.Client()
client.connect("localhost",1883,60)

client.on_connect = on_connect
client.on_message = on_message
client.loop_forever()
```

**Comment by ralight** [comment] 2018-09-25 12:56
This looks like a Paho Python question, not a Mosquitto question.

Anyway, the problem is that your publishing client quits before it has chance to send all of the messages. You must use `loop_forever()` or `loop_start()` to process the network communication.

I would also strongly strongly advise against using `eval()` on data straight from the broker, it is a big risk.

**Comment by ralight** [comment] 2018-09-27 12:07
Closing as per solution at https://stackoverflow.com/questions/52499406/unable-to-post-data-to-mosquitto-broker-continuously/52503797?noredirect=1#comment91960849_52503797

**Closed by ralight** 2018-09-27 12:07 UTC
