### ISSUE TITLE
Keep persistent sessions after mosquitto restart

### ISSUE THREAD

**Issue by nixikanius** [eclipse/mosquitto#769] opened 2018-04-06 10:43 UTC
I have a problem with losing of messages for persistence sessions which came after the mosquitto restarts until clients with persistence sessions reconnect. As for me, it seems that broker does not pay attention to sessions that existed before the mosquitto restart but wherein carefully saves all pending data to persistence db on shutdown.

So the problem scenario:

1. Start the mosquitto.
2. Start a client with persistence session, QoS 2 and subscription to some test topic.
3. Send test data to test topic.
3a. Test data successfully received by persistence client.
4. Stop persistence client.
5. Restart the mosquitto.
6. Send something else test data to test topic.
7. Start persistence client.
7a. **Test data from step 6 does not come to persistence client.**

The mosquitto key config parameters:

```
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/
autosave_interval 1
autosave_on_changes true
queue_qos0_messages true
```

Is there any way to solve the described problem?

**Comment by karlp** [comment] 2018-04-06 12:06
What version of mosquitto?  Are you sure you're using not just clean session=false, but also the same client id on both connections?  This is pretty core behaviour that people rely on day in, day out.

**Comment by nixikanius** [comment] 2018-04-08 21:06
I also think that case I described should be ordinal. I use mosquitto 1.4.12 in docker and tested mosquitto 1.4.15 too. As a persistent client, I use [telegraf](https://github.com/influxdata/telegraf) 1.5.3 [mqtt_consumer](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mqtt_consumer) which pushes data to InfluxDB.

There are not any problems with messages sent before mosquitto restart:

1. Start the mosquitto.
2. Start a client with persistence session, QoS 2 and subscription to some test topic.
3. Send test data to test topic.
3a. Test data successfully received by persistence client.
4. Stop persistence client.
5. Send something else test data to test topic.
6. Restart the mosquitto.
7. Start persistence client.
7a. Test data from step 5 successfully received by persistence client.

Think, above scenario should sufficiently demonstrate that telegraf client sets `clean session = false` and uses the same client id for all connections. The only problem is to deliver messages which sent between mosquitto restart and persistence client reconnects.

**Comment by ralight** [comment] 2018-04-08 21:55
Can you look at the persistence file saved by mosquitto when you stop it? You can use https://github.com/eclipse/mosquitto/tree/master/src/db_dump to get a more human friendly output.

You should be able to see the message that you've sent (or not!) as a combination of a DB_CHUNK_MSG_STORE and DB_CHUNK_CLIENT_MSG. The store contains the original topic, payload and some other bits, the client message contains a link to the stored message plus some client specific information. If you don't see the client message, then nothing has been saved to the persistence file.

**Comment by nixikanius** [comment] 2018-04-08 22:37
Here the dump of DB got after shutdown of mosquitto:

```
$ ./mosquitto_db_dump mosquitto.db
Mosquitto DB dump
CRC: 0
DB version: 3
DB_CHUNK_CFG:
	Length: 10
	Shutdown: 1
	DB ID size: 8
	Last DB ID: 102
DB_CHUNK_CLIENT:
	Length: 20
	Client ID: telegraf
	Last MID: 0
	Disconnect time: 1523225916
DB_CHUNK_SUB:
	Length: 24
	Client ID: telegraf
	Topic: smarthome/#
	QoS: 2
```

Think, mosquitto saves data about persistence session of telegraf. But when I send messages after mosquitto start before persistence session alive, nothing is saved to DB: dump is the same, DB file last change date does not change. After second shutdown of mosquitto dump is the same too.

Looks like mosquitto ignores all messages of persistence sessions existed before mosquitto restart if these sessions do not alive.

**Comment by nixikanius** [comment] 2018-04-12 21:05
I am embarrassed to write about it, but I tested VerneMQ for the first scenario in the same test environment and it works as expected - no one message is lost between broker restart and persistence client alive.

Unfortunately, I do not want to use VerneMQ, I like mosquitto. Due to using [ugly client lib](https://github.com/knolleary/pubsubclient) which can send only QoS 0 messages, only mosqutto could be my choice.

It almost seems that I noticed the significant bug with persistence functionality in mosquitto.

**Comment by ralight** [comment] 2018-04-12 21:32
It's nice to hear you say that, so let's get this sorted out. I have two questions to try to point us in the right direction:

Does this problem exist if you don't use docker?
How do you restart mosquitto? (more importantly - how do you stop mosquitto?)

**Comment by nixikanius** [comment] 2018-04-13 16:45
1. Yes, the problem exists if I do not use docker. I tested last version of mosquitto in bare Debian 9 system.
2. There is not any difference of stop/restart type. I tried to restart with init script or run mosquitto in console and stop it with CTRL-C. In both cases result is the bug is present.

In conclusion of bug description. There are not any losses of messages sent between persistence client stop and mosquitto restart. The only messages lost is that was sent between mosquitto restart and persistence client alive.

**Comment by rgaufman** [comment] 2019-05-04 16:39
I had a similar issue today:

1. Everything was running just fine for days
2. Mosquitto segfaulted for some reason:
```
[7131600.785888] mosquitto[30647]: segfault at 0 ip 00007f6d8c8e453c sp 00007ffc211e1678 error 4 in libc-2.27.so[7f6d8c75f000+1e7000]
```
3. This caused my MQTT consumer client to die
4. Mosquitto was restarted by systemd
5. All clients re-connected and started sending messages
6. I only realised my MQTT consumer is dead a few hours later
7. When starting my MQTT consumer, it subscribed to the topic, but all the messages since the segfault were gone :(

I am using a persistent connection with clean_session=false

Any solution to this?

**Comment by tra0815** [comment] 2019-06-18 13:50
I had exactly the same issue with the docker image.
No db file was written and so nothing persisted.
Found this error after a while:
`Error saving in-memory database, unable to open /mosquitto/data/mosquitto.db.new for writing.`

After changing the permissions, everything worked as expected.

Seems to me as an error of the docker image, creating the folders as root but afterwards running as user mosquitto.

tra

**Comment by rgaufman** [comment] 2019-06-19 09:51
Short update, I have switched to EMQx on the server side and using Mosquitto on each IoT hub, this seems to be working well so far. Mosquitto is fantastic but seems it has some edge cases where it can misbehave with 500+ intermittent bridge sessions.

**Comment by jr-dimedis** [comment] 2020-01-30 14:34
I have an update on this: I encounter exactly the same problem and found out that it happens only when ACL's are activated.

Without any ACL's subscriptions of persistent clients are restored properly after mosquitto restart.

If I enable ACL's (even most generic ones like "topic readwrite #") it stops working. I tried with user specific topic ACL's as well as "pattern" ACL's using "%u" or "%c" - same result. The "allow_anonymous" option makes no difference, so it's not about authentication.

I tested with mosquitto 1.6.8 on Ubuntu 16.04.6 / 18.04.2 x86_64 and could reproduce the problem using the steps described at top of this issue using mosquitto_sub and mosquitto_pub clients.

For your convenience I attached some scripts and minimal configs as a zip file. With these scripts you can easily reproduce the issue (use separate terminals for each script):

[mosquitto-issue-769.zip](https://github.com/eclipse/mosquitto/files/4134316/mosquitto-issue-769.zip)

```bash
./start-broker.sh # sets up passwd and starts broker with minimal mosquitto.conf
./sub.sh # subscribes to "#" with persistent session
# stop sub.sh
# stop the broker (and it will "forget" the subscription)
./start-broker.sh # start the broker again
./pub.sh # publishes current timestamp to some topic; just execute it 2 or 3 times
./sub.sh # should print the missed messages - but this doesn't happen
./pub.sh # publish again
# the message appears in the sub.sh shell, so the happy path is fine
```

I would highly appreciate any help on this. Probably I am doing things wrong with the ACL's or whatever? BTW: just comment out the "acl_file" parameter in mosquitto.conf and repeat the steps above: no messages get lost.

Just to make this clear. It's **not about messages not being queued** resp. persisted to disk on daemon restart. Only subscriptions without queued messages get lost.

Reproduce as follows:

```bash
./start-broker.sh
./sub.sh
# stop ./sub.sh
./pub.sh # message is queued
# stop broker
./start-broker.sh
./sub.sh # missed message is received
```

**Comment by ralight** [comment] 2020-01-30 16:52
@jr-dimedis brilliant, thanks very much I'll take a look.

**Comment by ralight** [comment] 2020-01-30 22:17
Hmm, ok so this is fun. The problem comes about because there isn't a tight coupling between the username and client id in MQTT. The client id is the most important factor for client identification (unsurprisingly), but the username and password makes more sense for authentication. There is nothing to stop a client using different usernames for the same client id.

As such, mosquitto doesn't currently save the username for a client in the persistence file, only the client id. What you see is that when you restart the broker, the client and its subscription are loaded from the persistence file, but with no username. Because there is no username for the client, the ACL check fails when you try to publish to it. The subscription is still there, but it messages published to it are rejected. By contrast, when you connect the subscriber again, the username is associated with the client instance and hence the ACL check will succeed.

The obvious thing to do here is to save the last used username in the persistence file, I'm not sure if that has other bad consequences though.

**Comment by jr-dimedis** [comment] 2020-01-31 08:22
@ralight Thanks for taking a look at this so quickly. Hopefully this can be solved the "obvious" way without much hassle. I am looking forward to it ;)

**Comment by g-andalf** [comment] 2020-05-29 11:49
Is there a plan fix this?
Or is therre a rationale not to fix?

**Comment by ralight** [comment] 2020-08-07 15:41
This is now fixed in the fixes branch.

**Closed by ralight** 2020-08-07 15:41 UTC
