### ISSUE TITLE
missing fail feedback if user not allowed to publish in topic

### ISSUE THREAD

**Issue by OliverSanftleben** [eclipse/mosquitto#229] opened 2016-07-29 08:31 UTC
It seems that if a user has read only permissions on a topic he's getting no negative feedback if he tries to publish into the same topic.

my acl file:
user gcread
topic read germany/#
topic read spain/#
topic read $SYS/broker/#
user gcwrite
topic write germany/#
topic write spain/#

mosquitto_pub -t "spain/balearicIslands" -m "message" -q 2 -u superadmin -P superadmin
Connection Refused: not authorised.
Error: The connection was refused.
mosquitto_pub -t "spain/balearicIslands" -m "message" -q 2 -u gcread -P gcread
-> no error message

**Comment by ralight** [comment] 2016-07-29 09:28
This is a limitation of the current MQTT spec, there is nothing that can be done about it at the moment I'm afraid.

**Comment by OliverSanftleben** [comment] 2016-07-29 09:45
I'm wondering that also with qos 2 there is no failure.

With MQTTClient from paho I'm getting no error in deliveryComplete , so everything seems working, but messages were never published with wrong permissions.

**Comment by ralight** [comment] 2016-07-29 10:00
Like I said, there is no mechanism for the broker to report failure of a PUBLISH, never mind the QoS. Hopefully this will be solved in a future version of MQTT.

**Comment by ralight** [comment] 2016-08-08 21:03
I'm closing this as `not a bug` because it isn't a problem with mosquitto as such,

**Closed by ralight** 2016-08-08 21:03 UTC
Labels: not a bug
