### ISSUE TITLE
Mosquitto 2.0.18 : message received during disconnection lost

### ISSUE THREAD

**Issue by MathiasLopes** [eclipse/mosquitto#3074] opened 2024-06-24 15:15 UTC
I'm currently experiencing a problem with versoin 2.0.18. When I publish a message on a topic and the client who is supposed to receive the message is disconnected, after reconnecting he can't retrieve his message.
My configuration is fine because I've tested it with other broker messages and it works.
CleanSession=false
Subscription=QoS 1
Send message = QoS 1
However, the subscription is recovered because if I send a message from the publisher after reconnecting the receiver, he receives the new message without having to subscribe to the topic again. 
What's more, with the same configuration, downgrading to Mosquitto version 1.6, the system works.

I use this image : https://hub.docker.com/_/eclipse-mosquitto

**Comment by MathiasLopes** [comment] 2024-06-26 14:05
After somes tests, the last version where it's worked is the 2.0.11

**Comment by ckrey** [comment] 2024-06-27 07:46
@MathiasLopes can you elaborate which client software you use and the steps necessary to reproduce the proble?
I cannot reproduce your problem with mosquitto_pub/sub

**Comment by MathiasLopes** [comment] 2024-06-27 08:00
@ckrey I have used twos differents clients softwares : MQTTX and the other is my self implementation with MQTTnet. 
For the steps :
1. Client1 (publisher) => Connect
2. Client2 (subscriber) => Connect with CleanStart=false
3. Client2 => Subscribe to topic "clean_session_false" with QoS1 
4. Client1 => Send message to topic "clean_session_false" with QoS1
5. Client2 => Receive message
6. Client2 => Disconnect
7. Client1 => Send message to topic "clean_session_false" with QoS1
8. Client2 => Reconnect with CleanStart=false

At this point, with CleanStart=false, the subscriber should retrieve every subscription (this works because if I send another message from client1, client2 receives it), but it should also retrieve missed messages, and this is not the behavior that occurs.

Thank you for your reply

**Comment by ckrey** [comment] 2024-06-27 09:46
I assume you are using MQTTv5 (CleanStart was defined in MQTTv5).

I cannot reproduce your problem with MQTTX, it works as expected.

In your own implementation, do you set the "Session Expiry Interval"  explicitly? This is important because the default is zero, which means the session is discarded by the broker on disconnect.
If this is not the problem, please attach the relevant part of the log file `/mosquitto/log/mosquitto.log`

**Comment by llamaonaskateboard** [comment] 2024-07-02 12:28
This is a duplicate of https://github.com/eclipse/mosquitto/issues/2618 which I just tracked down.

**Closed** 2024-07-10 11:33 UTC
