### ISSUE TITLE
Malformed/corrupted retained message after restart

### ISSUE THREAD

**Issue by bgernert** [eclipse/mosquitto#1161] opened 2019-02-14 07:31 UTC
Hi,
I am running Mosquitto 1.4.15 from the Ubuntu 18.04 repositories.
Currently I am trying to store a retained message in a persisted way, so if the broker is shut down (due to whatever reason) the messages are still there after restart.
This works as long as the broker is running. After a restart, the retained message gets malformed/corrupted. 

`mosquitto_pub  -h <host> -p 8883 -u <user> -P <pass> --capath /etc/ssl/certs/ -t "/test/hi" -m "Test 123" -r`

`mosquitto_sub -h <host> -p 8883 -u <user> -P <pass> --capath /etc/ssl/certs/ -t "#" -v
/test/hi Test 123`

Now I restart the broker and after a reconnect of mosquitto_sub I get:

```
mosquitto_sub -h <host> -p 8883 -u <user> -P <pass> --capath /etc/ssl/certs/ -t "#" -v
/test/hi Test 123
/test/hi `��EV
```

Any idea what is going wrong here?

**Comment by ralight** [comment] 2019-02-14 12:29
Does this definitely reproduce when you are starting the broker with a fresh config and persistence file? You're not the only person to have seen this, but at the moment my best guess that it is because of a mistake in the previous patch update which could corrupt the payload, but would be unlikely to get as far as saving the persistence file out.

I've tried to reproduce it on 18.04 using the package from the repo and have been unable to so far.

**Comment by ralight** [comment] 2019-02-14 17:50
If you update to the latest Ubuntu 18.04 version this should be fixed, based on the time of your report I don't believe the update was available for you then.

**Comment by bgernert** [comment] 2019-02-14 18:27
You are correct, it is working now!
Tank you!

**Comment by ralight** [comment] 2019-02-14 22:00
Great, and I'm sorry for the trouble.

**Closed** 2019-02-14 22:00 UTC
