### ISSUE TITLE
Cannot install libraries for raspberry pi

### ISSUE THREAD

**Issue by newbie8888** [eclipse/mosquitto#586] opened 2017-10-13 03:39 UTC
Please help... I cannot get past this issue. Using the latest version of Raspbian as of 10/10/2017. Followed install instructions from Mosquitto website to install for Pi. These are the errors I get:

raspberrypi:/etc/apt/sources.list.d $ sudo apt-get install mosquitto
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mosquitto : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
             Depends: libwebsockets3 (>= 1.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

AND>>>>

raspberrypi:/etc/apt/sources.list.d $ sudo apt-get install picap
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 picap : Depends: libmosquitto-dev but it is not going to be installed
         Depends: python-mosquitto but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by masterhou** [comment] 2017-10-24 06:36
you need install libssl1.0.0 and libwebsockets3 first.
sudo apt-get install  libssl  libwebsockets3

**Comment by schaumannj** [comment] 2017-11-09 19:59
looks like duplicate of #529

**Comment by PierreF** [comment] 2018-01-04 11:09
Closing as duplicate of #529 (and I think #529 is only a duplicate of #581)

**Closed by PierreF** 2018-01-04 11:09 UTC

**Comment by sharatkanthi** [comment] 2018-04-16 10:41
This is because the web socket library is not installed. Try running 
Code: Select all

sudo apt-get install libwebsockets-dev
before running 
Code: Select all

sudo apt-get install mosquitto
