### ISSUE TITLE
'mqtts' is not correct service name for port 8883

### ISSUE THREAD

**Issue by deviance** [eclipse/mosquitto#871] opened 2018-06-29 06:50 UTC
According to IANA [1], the name of the service on port 8883 is 'secure-mqtt'.
Could you please add support for IANA-assigned service name to -L switch?

[1]  https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=8883

**Comment by karlp** [comment] 2018-06-29 10:22
Could you clarify what yhou expect to be changed here?

There's nothing in iana port names that has anything do to with protocol methods.

**Comment by deviance** [comment] 2018-06-29 12:39
@karlp 
I expect that running `mosquitto_pub {-L,--url} secure-mqtt://host.org/topic ...` does not result in "Error: unsupported URL scheme.", but behaves the same way as `mosquitto_pub {-L,--url} mqtts://host.org/topic ...`.

The "mqtts" (sensors? secure?) scheme naming is considered confusing. Discussion is [here](https://mqtt.org/2013/12/mqtt-for-sensor-networks-mqtt-sn)

**Comment by ptjm** [comment] 2018-07-02 17:37
@deviance, it's very hard to agree with your logic. The IANA port name assignments are not a standard for URI schemes, and there are any number of examples where the name assigned to the port is not used in a correct URI (think ftps, which was assigned port 990 by the IANA but standardized on port 22 by the IETF, or sftp, which uses port 22, ssh). I don't believe the URI scheme for mqtt is part of any standard, but if we accept mqtt.org as the repository of common practice, the URIs recommended there (https://github.com/mqtt/mqtt.github.io/wiki/URI-Scheme) (OK, it's a wiki entry on github, but that's where the mqtt.org wiki is) is to use mqtt:// and mqtts://. So, there's no standards-based argument to be made about this, but mosquitto is certainly following the closest thing to a standard URI format for mqtt and mqtts.
I just did a web search and found a couple of cases where the URIs use schemas "tcp" and "ssl", so clearly implementations don't universally follow the recommendations on mqtt.org, but maybe they should because they're clearly not capable of choosing good names on their own.

As far as confusion is concerned, using anything other than mqtts as the URI scheme for the TLS-encrypted version of a protocol with URI scheme mqtt would be confusing to pretty much anyone, except maybe people who think using "tls" and "ssl" is a good idea. The argument made in your link is that using the name mqtt-s for something that is *not* mqtt over TLS was confusing,. This is not exactly arguing against using the current URI schemes. Personally, I think the resulting name mqtt-sn is still confusing and perhaps there'd be more uptake outside the original problem domain if they tried something more descriptive, like "Connectionless MQTT" or "MQTT for Datagrams".

**Comment by toast-uz** [comment] 2018-07-14 13:03
Anyway, closing because this is not a bug. Further discussion should be made at  https://groups.google.com/forum/#!forum/mqtt .

**Closed by toast-uz** 2018-07-14 13:03 UTC
