### ISSUE TITLE
Broken comparison of boolean values in CMakeLists.txt

### ISSUE THREAD

**Issue by mojca** [eclipse/mosquitto#1101] opened 2019-01-06 08:11 UTC
The boolean options in CMake should not be compared with `STREQUAL`, but as boolean values instead, so that even `-DUSE_LIBWRAP=yes` would work, for example, see the [CMake documentation](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/VariablesListsStrings#boolean-values-in-cmake).

For example, the following
```cmake
if (${USE_LIBWRAP} STREQUAL ON)
	set (MOSQ_LIBS ${MOSQ_LIBS} wrap)
	add_definitions("-DWITH_WRAP")
endif (${USE_LIBWRAP} STREQUAL ON)
```
would probably better be written as
```cmake
if (USE_LIBWRAP)
	set (MOSQ_LIBS ${MOSQ_LIBS} wrap)
	add_definitions("-DWITH_WRAP")
endif (USE_LIBWRAP)
```

**Comment by slewsys** [comment] 2019-01-07 20:41
The problem is aggravated by the fact that the [Build Dependencies](
https://github.com/eclipse/mosquitto#build-dependencies) section of [Mosquitto's readme.md](
https://github.com/eclipse/mosquitto/blob/master/readme.md) explicitly uses "yes" and "no" boolean values, contrary to the tests in [CMakeLists.txt](
https://github.com/eclipse/mosquitto/blob/master/CMakeLists.txt) as per [Mojca's comment](
https://github.com/eclipse/mosquitto/issues/1101#issue-396238010).

**Comment by ralight** [comment] 2019-01-10 15:54
Thanks for the report and example. It's also nice to have a change which brings a functional improvement and makes it more readable all at the same time.

Closed in https://github.com/eclipse/mosquitto/commit/8fce26134b0d993df47174d6620ea21d54bff4e0 , which will be part of 1.5.6 soon-ish.

**Closed by ralight** 2019-01-10 15:54 UTC

**Comment by mojca** [comment] 2019-01-10 16:11
Thank you very much for the super quick fix.
