### ISSUE TITLE
bridge problem

### ISSUE THREAD

**Issue by zhangxichao** [eclipse/mosquitto#2201] opened 2021-05-08 08:23 UTC
I test the bridge function, and I deploy mosquitto on the embedded motherboard and x86(ubuntu14.04) host respectively.
X86 is the remote broker, and embedded is the local broker. No problem with normal operation.
I deliberately end the x86 broker and then start it to test the bridge reconnection. I will encounter the situation that the bridge can not be connected, and it will never be connected.

embedded motherboard print:
112358: Connecting bridge bridge_01 (192.168.1.254:1885)
......

x86:
1620461694: Client unknown closed its connection.
1620461702: New connection from 192.168.1.136:55356 on port 1885.
1620461762: Client unknown closed its connection.
1620461782: New connection from 192.168.1.136:55357 on port 1885.
1620461842: Client unknown closed its connection.
......

**Comment by ralight** [comment] 2021-05-08 22:41
I'm sorry, Ubuntu 14.04 is no longer supported by Mosquitto because the version of openssl is too old and way out of date. If you are using the mosquitto provided in the Ubuntu 14.04 repositories you are using a version that is over 9 years old.

**Comment by zhangxichao** [comment] 2021-05-09 14:34
No, you misunderstood me. I use version 2.0.9, I compile version 2.0.9 source code.

**Comment by anubias** [comment] 2021-05-11 13:58
We experience a similar problem with 2.0.10.

We are using mosquitto 2.0.10 in an embedded Linux device, and it connects to an Iot-HUB. Customer noticed that when the Internet connectivity is recovering after a temporary down-time, mosquitto cannot reconnect even though it seems to be trying, by looking at the logs. I have tested this locally as well, by blocking the MQTT traffic (both incoming and outgoing) using the firewall and it doesn't reconnect when the traffic is enabled again. 

However, testing briefly with mosquitto 2.0.7, it seems to re-connect (but has other issues we are affected of, like the 100% CPU load). So there was some regression on that front in between 2.0.7 and 2.0.10 (or even 2.0.9 according to OP).

**Comment by zhangxichao** [comment] 2021-05-12 08:23
@anubias 
I tested version 2.0.7. There will also be problems of reconnection.
Embedded Linux runs version 2.0.7, and Ubuntu runs version 2.0.9.
Turn off remote mosquitto broker (Ubuntu), when the embedded end appears

"27828: Connecting bridge bridge_01 (192.168.1.254:1883)"

now, if you start remote broker, you will encounter the problem that I mentioned earlier that you can't connect.
How do you test it? Will you be in the same situation as me?

**Comment by anubias** [comment] 2021-05-12 08:55
@zhangxichao
In my case, the mosquitto bridge connects to an IoT-HUB on Azure and it is that connection which I am having trouble, not the local connection from my monitoring SW (not sure if that is your issue or not).

So in order to test the reconnection to the IoT-HUB, I am activating a firewall between the embedded device and the Internet, which blocks the MQTT ports used. With 2.0.7 when the firewall is disabled, it reconnects and sends all the messages that it stored while disconnected, but with 2.0.10 it doesn't manage to reconnect at all unles i restart mosquitto.

In both versions the logs look similar (I couldn't spot differences), so both version do try to periodically reconstruct the sockets.

**Comment by zhangxichao** [comment] 2021-05-12 09:05
@anubias You try to turn off the firewall when "connecting" appears on the embedded Linux

**Comment by anubias** [comment] 2021-05-12 09:08
@zhangxichao So, i turn "on" the firewall for many hours (traffic is blocked to Internet), then at some point (regardless what it says on the log, at which point the mosquitto bridge logs "connecting" or something else) I turn "off" the firewall (which means that traffic is re-enabled). And then shortly after (usually a minute or two) the 2.0.7 mosquitto bridge manages to reconnect, and 2.0.10 doesn't (even many hours later).

**Comment by zhangxichao** [comment] 2021-05-12 09:14
@anubias  Maybe our testing methods are not the same. My test environment is to turn off the remote mosquito to block the connection. When the embedded Linux side is printing "connecting", the problem of reconnection will occur.

**Comment by zhangxichao** [comment] 2021-05-12 09:22
It is estimated that azure will restart one day, and this problem will appear. Of course, this will not happen, and azure will not restart. But you can verify that you can remove your iot-hub, do not use the firewall, and then "connecting" appears to connect the hub again.

**Comment by ralight** [comment] 2021-05-17 13:55
That's interesting that you have 2.0.7 working ok, I've just addressed a bug around bridge reconnections that was introduced in 2.0.6. Are you able to try by compiling from the `fixes` branch? Let me know if you would like help with that.

**Comment by anubias** [comment] 2021-05-17 15:06
We can give it a shot, of couse. At our timezone it's quite late in the day today (past office hours), so we will try it tomorrow.

**Comment by ralight** [comment] 2021-05-17 15:07
That would be good, thank you.

**Comment by anubias** [comment] 2021-05-18 11:45
I am already testing the fixes-branch, and early results are positive. It seems the connection is re-established. I'll keep testing further...

**Comment by anubias** [comment] 2021-05-18 13:49
So yes, i can confirm that the connection is re-established and data flow is resumed. So the fixes branch fixes this problem.
Now (if you don't mind @ralight), do you know when is the next scheduled release? When can we expect to have a release with these fixes in?

**Comment by ralight** [comment] 2021-05-18 15:52
@anubias A bugfix release is overdue, so "soon", is that good enough? :)

**Comment by anubias** [comment] 2021-05-27 08:43
@ralight Sorry to bother you, but almost two weeks have passed. Are you able estimate to us what "soon" could be? I ask because we need to make a release, and we need to know whether we will wait more for this correction or whether we should roll back.

**Comment by ralight** [comment] 2021-05-28 09:45
Lots of things got in the way this week, I'm planning on making a release on Tuesday/Wednesday.

**Comment by anubias** [comment] 2021-05-28 10:03
@ralight Thank you very much for the reply! Good luck!

**Comment by ralight** [comment] 2021-08-24 10:56
I think I missed this issue off the changelog, or it got mixed up with #2207, which is why it hasn't been closed. Closing now as 2.0.11 was released.

**Closed by ralight** 2021-08-24 10:56 UTC
