### ISSUE TITLE
Broker error on include_dir permissions on HUP

### ISSUE THREAD

**Issue by chelliwell** [eclipse/mosquitto#857] opened 2018-06-13 06:59 UTC
If the configured include_dir has incorrect permissions (e.g. drwx------, and owned by root; with mosquitto running under non-root user), then the broker starts up ok and uses the included conf(s), but if then sent a SIGHUP:

Jun 13 07:49:43 wgs daemon.info mosquitto[908]: Reloading config.
Jun 13 07:49:43 wgs daemon.err mosquitto[908]: Error: Unable to open include_dir '/etc/mosquitto/include.d'.

I guess this is because, at start up, the config is read *before* the dropping of user privileges, and permissions are not re-checked afterwards.

**Comment by toast-uz** [comment] 2018-07-29 07:47
I'd like to reconfirm your situation.
- Run mosquitto by root user.
- Successfully read mosquitto.conf under the permission root user can only read.
- Mosquitto.conf describes mosquitto's non-root user.
- Mosquitto broker daemon run as the non-root user.
- Sent a SIGHUP
- Fail to read mosquitto.conf due to incorrect permission.
Right?
So what is the problem?

**Comment by ralight** [comment] 2018-08-01 22:33
The point is that the config is read originally as the root user, so it succeeds. Sending the HUP and it failing is then unexpected.

**Comment by toast-uz** [comment] 2018-08-01 22:47
@ralight if mosquitto daemon run as the root, the config should be reloaded. But, if mosquitto daemon run as the non-root user, I guess the config should not be reloaded. This issue's situation is the latter. So I guess it's normal to fail to reload. I've misunderstood?

**Comment by momoskitto** [comment] 2019-02-06 17:07
This issue looks like a duplicate of
https://github.com/eclipse/mosquitto/issues/588

**Comment by ralight** [comment] 2021-02-03 22:36
It shouldn't be possible this occurs as of 2.0.

**Closed by ralight** 2021-02-03 22:36 UTC
Labels: bug, mosquitto-broker
