### ISSUE TITLE
disconnected clients - value is negative

### ISSUE THREAD

**Issue by SSathappa** [eclipse/mosquitto#2761] opened 2023-03-01 15:20 UTC
Hi,

In one of our mqtt instance observed negative value for clients disconnected
```
$SYS/clients/connected  	: 10558
$SYS/clients/disconnected 	: -8726
$SYS/clients/total 		: 2045 
Mosquitto Version: 2.0.14
```
what does the negative value signifies?

To this instance we have close to 3000+ IoT gateways are connected and while checking total client instance we noticed this negative values for disconnected clients.

Also, looked this older [thread](https://github.com/eclipse/mosquitto/issues/287), seems the issue is fixed.

Please clarify, is it anything to do with our client publisher programs?

**Comment by xrat** [comment] 2023-03-10 10:21
I think this is a duplicate of #2466

**Comment by ralight** [comment] 2023-04-01 09:39
Closing as a duplicate.

**Comment by ralight** [comment] 2023-04-01 09:39
(Thanks for the report though)

**Closed by ralight** 2023-04-01 09:39 UTC
