### ISSUE TITLE
Corrupt Mosquitto Database / Suddenly Stopped Sending Messages

### ISSUE THREAD

**Issue by rgaufman** [eclipse/mosquitto#1214] opened 2019-03-30 19:03 UTC
Hi there,

I have this mosquitto config on a handful of units which has been working beautifully:

```
pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest stdout

port 1883
allow_anonymous true
connection bridge-2d5d552da74a1c5f3602
address vpn-timeline:1883
topic # out 2
topic # in 2 tb/2d5d552da74a1c5f3602/ tb/2d5d552da74a1c5f3602/

bridge_protocol_version mqttv311
cleansession false
notifications true
keepalive_interval 29
idle_timeout 90
max_queued_messages 1000000
log_type all

remote_username 2d5d552da74a1c5f3602
remote_password xxxxxxx
```

All of a sudden, one unit stopped sending messages. I was tearing my hair out but the solution was to stop mosquitto, rename the mosquitto.db file and start it again.

I need to retrieve the messages from the mosquitto.db file but I have 2 questions:

1. What could be the cause of this to happen?
2. Are there any tools to recover the mosquitto.db file?

Here is the file: https://www.dropbox.com/s/9h1ejy8nd7xz077/20190330_mosquitto.db?dl=0

This is what I see when I start mosquitto with the corrupt db file (which doesn't work, messages don't go through):

```
Mar 30 18:59:14 TimeBox-2d5d552da74a1c5f3602 systemd[1]: Starting Mosquitto MQTT Broker...
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: mosquitto version 1.5.5 starting
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Config loaded from /etc/mosquitto/mosquitto.conf.
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Opening ipv4 listen socket on port 1883.
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Opening ipv6 listen socket on port 1883.
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Bridge local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 doing local SUBSCRIBE on topic #
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Connecting bridge bridge-2d5d552da74a1c5f3602 (vpn-timeline:1883)
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Bridge TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 sending CONNECT
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 systemd[1]: Started Mosquitto MQTT Broker.
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Received CONNACK on connection local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602.
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Bridge local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 sending UNSUBSCRIBE (Mid: 37234, Topic: #)
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Bridge local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 sending SUBSCRIBE (Mid: 37235, Topic: tb/2d5d552da74a1c5f3602/#, QoS: 2)
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Bridge local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 doing local SUBSCRIBE on topic #
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Received PUBACK from local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 (Mid: 37233)
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Received UNSUBACK from local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602
Mar 30 18:59:16 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972356: Received SUBACK from local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602
Mar 30 18:59:44 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972384: Sending PINGREQ to local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602
Mar 30 18:59:44 TimeBox-2d5d552da74a1c5f3602 mosquitto[9861]: 1553972384: Received PINGRESP from local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602
```

This is what I see when I start mosquitto without a db file (which works, messages are able to send):

```
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 systemd[1]: Starting Mosquitto MQTT Broker...
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 systemd[1]: Started Mosquitto MQTT Broker.
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: mosquitto version 1.5.5 starting
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Config loaded from /etc/mosquitto/mosquitto.conf.
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Opening ipv4 listen socket on port 1883.
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Opening ipv6 listen socket on port 1883.
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Bridge local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 doing local SUBSCRIBE on topic #
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Connecting bridge bridge-2d5d552da74a1c5f3602 (vpn-timeline:1883)
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Bridge TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 sending CONNECT
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Received CONNACK on connection local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602.
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Bridge local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 sending UNSUBSCRIBE (Mid: 2, Topic: #)
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Bridge local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 sending SUBSCRIBE (Mid: 3, Topic: tb/2d5d552da74a1c5f3602/#, QoS: 2)
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Bridge local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 doing local SUBSCRIBE on topic #
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Received PUBACK from local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602 (Mid: 1)
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Received UNSUBACK from local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602
Mar 30 19:00:30 TimeBox-2d5d552da74a1c5f3602 mosquitto[11341]: 1553972430: Received SUBACK from local.TimeBox-2d5d552da74a1c5f3602.bridge-2d5d552da74a1c5f3602
```

**Comment by ralight** [comment] 2019-04-11 20:30
I'll take a look at the file, in the meantime do you know what mosquitto version you were using, and where it was from?

**Comment by ralight** [comment] 2019-04-11 20:48
There is also https://github.com/eclipse/mosquitto/tree/master/src/db_dump which can dump a text form of the persistence file.

**Comment by ralight** [comment] 2019-04-11 20:49
(and I spotted the version number in the logs, sorry for that)

**Comment by rgaufman** [comment] 2019-04-11 20:58
Version is: 

```
ii  mosquitto                             1.5.5-1                           amd64        Package created with checkinstall 1.6.2
```

It was created like this:

```
sudo apt-get install uuid-dev libsystemd-dev libssl-dev checkinstall
wget http://mosquitto.org/files/source/mosquitto-[mosquitto_ver, eg: 1.5.7].tar.gz
tar xvvzf mosquitto-[mosquitto_ver].tar.gz
cd mosquitto-[mosquitto_ver]
sed -i 's/WITH_SYSTEMD:=no/WITH_SYSTEMD:=yes/' config.mk
sudo checkinstall --default --backup=no --deldoc=yes --install=yes --pkgname=mosquitto --pkgversion='[mosquitto_ver]'
```

Thank you for looking! - and I will check out db_dump, thank you!

**Comment by ralight** [comment] 2019-04-11 21:08
Ok, thanks for the info.

From what I can see, the persistence file is fine (but very helpful). Running `mosquitto_db_dump --stats <file>` you see:

```
DB_CHUNK_CFG:        1
DB_CHUNK_MSG_STORE:  205155
DB_CHUNK_CLIENT_MSG: 219973
DB_CHUNK_RETAIN:     2
DB_CHUNK_SUB:        2
DB_CHUNK_CLIENT:     2
```

Which tells us there 219973 messages waiting to be sent to a client, and those messages refer to 205155 stored messages, which are the bit that stores the original topic and payload and that sort of thing. There are also 2 retained messages, 2 subscriptions and 2 persistent clients.

Running without `--stats`, and just looking at the client messages, I see there are a few messages with state 7, which is "wait for pubrel", then the rest of the 219k messages are in state 11, which is "queued". It seems what has happened here is that some part of the communication has got confused and is waiting for messages that will presumably never come. Because they don't come and messages must be delivered in order, the queue will never empty. Now this shouldn't happen of course, so I'm going to try to figure out how it happened and how to make it unstick. I think this may be a problem unique to bridges.

**Comment by rgaufman** [comment] 2019-05-04 15:31
Hi there, thank you again for looking at this. This happened again today and I'm seeing the following running ```mosquitto_db_dump --stats /var/lib/mosquitto/mosquitto.db```

```
DB_CHUNK_CFG:        1
DB_CHUNK_MSG_STORE:  11012
DB_CHUNK_CLIENT_MSG: 11008
DB_CHUNK_RETAIN:     2
DB_CHUNK_SUB:        709
DB_CHUNK_CLIENT:     709
```

But new messages are being processed, but there is a gap of 5 hours when the MQTT consumer died :( - is there any way to get this to unstick? - also, any permanent solution for this?

**Comment by rgaufman** [comment] 2019-05-05 12:37
Ah, I think the issue yesterday was related to this rather than QOS2: https://github.com/eclipse/mosquitto/issues/769

But when I reset the database, there was 1 MQTT client (out of 700) that was stuck and was affected by this issue.

**Comment by rgaufman** [comment] 2019-05-30 11:17
We had the same situation happen again, mosquitto suddenly started chewing through gigabytes of ram. This time the mosquitto_db_dump command is not showing anything:

```
deployer@ctrl-01:~/mosquitto/src/db_dump$ ./mosquitto_db_dump --stats /var/lib/mosquitto/mosquitto.db
deployer@ctrl-01:~/mosquitto/src/db_dump$ echo $?
0
```

We have lost 5 hours of messages and the solution was to stop mosquitto, move the db file to another location and re-start mosquitto.

Here is the database file: https://www.dropbox.com/s/o2q7h2zqhpmyy96/mosquitto.db?dl=1

We are using version 1.6.2 and any help would be appreciated.

**Comment by ralight** [comment] 2019-05-30 21:03
Do your clients by any chance occasionally send a DISCONNECT command? There has been an issue fixed related to persistent clients not receiving messages after disconnecting with DISCONNECT. That will be in 1.6.3. It feels like it could be related.

**Comment by rgaufman** [comment] 2019-05-30 22:12
The client that stopped receiving messages does not send DISCONNECT commands, it is a permanent process that runs 24/7. Does the database shared above give any indication as to what could have happened?

**Comment by ralight** [comment] 2019-05-31 00:03
Not so far. I can see there are a large number of queued messages for timeline_consumer, TimeBox.bridge-* and TimeBox-*.bridge-*. When I start the broker and connect with those client ids, the messages are all delivered fine though as far as I can tell.

**Comment by ralight** [comment] 2019-05-31 21:54
My testing last night was incorrect, I'd forgotten it was bridges that were getting stuck.

I've done more work tonight and found some areas where the outgoing inflight messages count could get confused, leading to no messages being sent. I now have the situation that reloading your persistence file will result in the messages being delivered, whereas before they stopped after a short while. I don't know if this will also fix the cause of the problem, but it seems likely that they are related.

If you are able to test it out, the `fixes` branch contains the change, plus other fixes that will become part of 1.6.3.

**Comment by rgaufman** [comment] 2019-06-01 09:22
Thank you for looking into this! - I'm trying to compile from the fixes branch but getting this:

```
root@ctrl-01:~/mosquitto# make
...
cc  -Wl,--dynamic-list=linker.syms mosquitto.o alias_mosq.o bridge.o conf.o conf_includedir.o context.o database.o handle_auth.o handle_connack.o handle_connect.o handle_disconnect.o handle_ping.o handle_pubackcomp.o handle_publish.o handle_pubrec.o handle_pubrel.o handle_suback.o handle_subscribe.o handle_unsuback.o handle_unsubscribe.o logging.o loop.o memory_mosq.o net.o net_mosq.o net_mosq_ocsp.o packet_datatypes.o packet_mosq.o property_broker.o property_mosq.o persist_read.o persist_read_v234.o persist_read_v5.o persist_write.o persist_write_v5.o plugin.o read_handle.o security.o security_default.o send_auth.o send_connack.o send_connect.o send_disconnect.o send_mosq.o send_publish.o send_suback.o send_subscribe.o send_unsuback.o send_unsubscribe.o service.o session_expiry.o signals.o subs.o sys_tree.o time_mosq.o tls_mosq.o utf8_mosq.o util_mosq.o util_topic.o websockets.o will_delay.o will_mosq.o -o mosquitto  -ldl -lm -lrt -lssl -lcrypto
cc -I..  -Wall -ggdb -O2 -c mosquitto_passwd.c -o mosquitto_passwd.o
cc  mosquitto_passwd.o -o mosquitto_passwd  -lcrypto
make[1]: Leaving directory '/root/old/mosquitto/src'
set -e; for d in man; do make -C ${d}; done
make[1]: Entering directory '/root/old/mosquitto/man'
xsltproc --nonet libmosquitto.3.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
compilation error: file manpage.xsl line 3 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
compilation error: file libmosquitto.3.xml line 4 element refentry
xsltParseStylesheetProcess : document is not a stylesheet
Makefile:78: recipe for target 'libmosquitto.3' failed
make[1]: *** [libmosquitto.3] Error 5
make[1]: Leaving directory '/root/old/mosquitto/man'
Makefile:17: recipe for target 'docs' failed
make: *** [docs] Error 2
```

Any ideas?

**Comment by ralight** [comment] 2019-06-01 10:19
Use `make binary` to skip building the man pages, or install `docbook-xsl` on Debian/Ubuntu systems.

**Comment by rgaufman** [comment] 2019-06-01 11:09
Thank you that worked, I started mosquitto on another port with the database and it's now processing all the messages, thank you. Fingers crossed that will resolve the issue going forward once the new release is done :)

**Comment by ralight** [comment] 2019-07-02 10:48
Any comments on this now that 1.6.3 has been out for a while?

**Comment by rgaufman** [comment] 2019-07-13 00:01
I had some units where 1.6.3 was leaking memory, I deleted mosquitto.db and not had issues so far

**Comment by ralight** [comment] 2019-07-24 12:49
In that case I will close this for the moment, please reopen it if you have problems again.

**Closed by ralight** 2019-07-24 12:49 UTC

**Comment by sivann** [comment] 2019-10-17 07:59
Hello, this is to inform you  the issue still exists as the fix seems to exist only in the develop branch.
