### ISSUE TITLE
Test 06-bridge-b2br-remapping.py fails on v1.5

### ISSUE THREAD

**Issue by GAZ082** [eclipse/mosquitto#890] opened 2018-07-17 23:37 UTC
Hi there. I "make" successfully in a Pi Zero W (4.14.52+ #1123 Wed Jun 27 17:05:32 BST 2018 armv6l GNU/Linux) and when i test i get this:

```
/06-bridge-b2br-remapping.py
1531870045: mosquitto version 1.5 starting
1531870045: Config loaded from 06-bridge-b2br-remapping.conf.
1531870045: Opening ipv4 listen socket on port 1889.
1531870045: Opening ipv6 listen socket on port 1889.
1531870045: Connecting bridge bridge_sample (localhost:1888)
1531870045: Bridge minotauro.bridge_sample sending CONNECT
1531870045: Error creating bridge: Connection refused.
1531870045: Warning: Unable to connect to bridge bridge_sample.
1531870045: New connection from ::1 on port 1889.
1531870045: Socket error on client <unknown>, disconnecting.
1531870049: mosquitto version 1.5 terminating

Traceback (most recent call last):
  File "./06-bridge-b2br-remapping.py", line 111, in <module>
    (bridge, address) = ssock.accept()
  File "/usr/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
socket.timeout: timed out
Makefile:76: recipe for target '06' failed
make[2]: *** [06] Error 1
make[2]: Leaving directory '/home/pi/mosquitto-1.5/test/broker'
Makefile:15: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/home/pi/mosquitto-1.5/test'
Makefile:43: recipe for target 'test' failed
make: *** [test] Error 2
```

I compiled with the websockets option.

Thanks.

**Comment by toast-uz** [comment] 2018-07-21 01:44
I confirmed this issue on v1.5 although not on v1.4.15. So it is definitely a bug.
Could you rename the subject to such a "Test 06-bridge-b2br-remapping.py fails on v1.5" in order to describe the issue clearly?

**Comment by toast-uz** [comment] 2018-07-21 06:17
I identified the first bad commit by using git_bisect.

```
5d2f5c25d7542f0530165947829e706fceda236f is the first bad commit
commit 5d2f5c25d7542f0530165947829e706fceda236f
Author: Roger A. Light <roger@atchoo.org>
Date:   Sun Apr 15 23:25:04 2018 +0100

    Experimental parallel testing for broker.

:100644 100644 75440f2c83310c1d591c402d845affbf9c54964a f17d0e19b6a213b9a4499012540e97a56473ec08 M	Makefile
:040000 040000 a26c04471524249a127d56a961dd004b46092991 f28ca9a085f88c52693abf30f64cef2f1c991818 M	test
```

This commit changes only test code. I'm not sure for the reason, but it seems by some experimental needs. Therefore, I understood this is not a bug. @GAZ082 what do you think about that?

**Comment by GAZ082** [comment] 2018-07-21 17:17
@toast-uz Modified the subject as requested. I just went ahead and Mosquitto is working fine, so It may be the test was made for another thingie non critical.

I think this test should not be in a "end user" release, it belongs to a dev branch. Dont know, i'm not a pro dev, I bet you have a much better judgement.

**Comment by toast-uz** [comment] 2018-07-21 20:07
Thanks @GAZ082 . Keep this issue until @ralight show his intent of the test.

**Comment by ralight** [comment] 2018-08-02 00:17
I do not see this, but haven't tried it out on an arm device recently. If it had failed for me on a Pi, there wouldn't be any arm debs. I'll take a look. Is there anything special about your network setup or anything else that would help?

**Comment by toast-uz** [comment] 2018-08-02 03:57
@ralight I've reproduced on Cent7. It's not the arm specific issue.

**Comment by toast-uz** [comment] 2018-08-05 13:08
This issue solved by the first commit of #864 . The reason is as same as #507 .

**Comment by toast-uz** [comment] 2018-08-05 21:35
More essentially, the root cause seems the bridge cannot reconnect when it fails to connect with the first real address of bridge target hostname, although the hostname has several real addresses.

**Comment by ralight** [comment] 2018-08-08 13:05
the PR from #864 is now merged to the `fixes` branch, would you please be able to test it out and close the issue if it works for you? (I am aware there are some other tests that fail, I'm working on them now but am just interested in the remapping test here).

**Comment by toast-uz** [comment] 2018-08-08 14:10
The remapping test has passed on Cent7 for me. Wait @GAZ082 's response.

**Comment by GAZ082** [comment] 2018-08-08 17:14
It works now!

**Comment by ralight** [comment] 2018-08-08 19:34
Lovely, I'll close the issue then :)

**Closed by ralight** 2018-08-08 19:34 UTC
Labels: bug, pending-close
