### ISSUE TITLE
mosquitto on raspbian stretch ?

### ISSUE THREAD

**Issue by heiko2402** [eclipse/mosquitto#630] opened 2017-11-23 08:26 UTC
hi. how can i install mosquitto on raspbian stretch, always get error message.

**Comment by toast-uz** [comment] 2017-11-30 12:22
Installing on raspbian is very frequently asked. Please search it in issues.
Sorry too many open issues to search.

**Comment by PierreF** [comment] 2018-01-04 10:58
Closing as duplicate of #529

**Closed by PierreF** 2018-01-04 10:58 UTC
