### ISSUE TITLE
Get list of connected clients 

### ISSUE THREAD

**Issue by prasadnadendla** [eclipse/mosquitto#655] opened 2017-12-21 19:05 UTC
Is there a way to fetch list of active client ids? I tried using the **$SYS/broker/clients/connected**  topic but it's only giving the count of connected clients NOT the client id details

**Comment by ralight** [comment] 2017-12-21 21:40
No, this isn't possible, but is something that you could implement in your application layer.

**Comment by prasadnadendla** [comment] 2017-12-22 19:03
can we expect this feature in the next release ? Also what's the best practice to handle at application layer ?

**Comment by ralight** [comment] 2017-12-22 22:51
No, it's unlikely that this would ever be supported.

You should try to come up with a scheme that works for the requirements that you have.

**Comment by toast-uz** [comment] 2017-12-22 23:44
Seems to similar with #622 .

**Comment by PierreF** [comment] 2018-01-04 15:24
Closing as duplicate of #622

**Closed by PierreF** 2018-01-04 15:24 UTC
