### ISSUE TITLE
Not a "Bug" But a question

### ISSUE THREAD

**Issue by muhammad-haroon** [eclipse/mosquitto#321] opened 2016-11-24 21:41 UTC
Hi, 
i am using mosquitto in a really basic pub/sub scenario but within the same process  i.e the publisher and subscriber are in the same process , but in different threads, but this doesnt seem to work, i surely am doing something wrong, can you guys please shed some light on it, for my better understanding.
Regards
Haroon

**Comment by muhammad-haroon** [comment] 2016-11-25 14:46
Sorry about the basic description , a more detailed description is , 
i dont know if this is a bug. or an enhancement is needed , i might be wrong, but the thing is within the same process a single client associated with a client id cant be a subscriber and a publisher at the same time even when the subscriber and publishing parts are in seprate threads, i think there should  be a flexibility for a client associated with a single client id using the same mosquito object/struct/handle returned from mosquitto_new should be able to subscribe and publish from within the same process it should be upto the user / developer to make the publishing and subscribing thread safe etc, but at this point in time publishing and subscribing require seprate client_ids / seprate mosquitto handles.

**Comment by karlp** [comment] 2016-11-25 21:19
No, it works just fine.  Perhaps if you described more what sort of problems you were having?  Even in just single threaded, single process, there's no problem having both subscriptions and publishing going on with the same mosquitto client object.

**Comment by ralight** [comment] 2016-11-26 09:32
If you're running your own threads you need to use mosquitto_threaded_set() as described at the top of mosquitto.h:

 *  If your application uses threads you must use <mosquitto_threaded_set> to
 *  tell the library this is the case, otherwise it makes some optimisations
 *  for the single threaded case that may result in unexpected behaviour for
 *  the multi threaded case.

**Comment by muhammad-haroon** [comment] 2016-11-26 13:10
Hi , 
i am using mosquitto.h without any clients such as mosquittopp , just straight up mosquitto.h , i have got a really simple sample code , if you want i can send it over to you , the problem i am having is , if i have a mosquitto object intialized by mosquitto_new with client id e.g abc and if i use it to subscribe to the same topic i am publishing to using again the same object returned by mosquitto_new above the message callback never gets called, if i intialize a new mosquitto object with a different client id and subscribe in a different thread i get the mssages back,

**Comment by muhammad-haroon** [comment] 2016-11-26 13:11
and i cant seem to find the mosquitto_threaded_set function in mosquitto.h , am i using the wrong version of mosquitto.h

**Comment by ralight** [comment] 2016-11-27 21:11
The latest version is 1.4.10 - you should be able to see what version you are using from the mosquitto.h defines.

**Comment by muhammad-haroon** [comment] 2016-11-28 20:02
Hi , please dont mind my questions /suggestions i understand that i might be using mosquitto wrongly , but i am using mosquitto in a multithreaded enviroment, and i monitored the log , along with debugging my code, it so happens that on the broker , a SUBACK message is printed, from this i take that a subscription acknowledgement has been sent to the client, but on the client side the subscribe callback doesnt get called, neither do the the message callback gets called .
, i am using mosquitto_loop in my own loop to ping the broker after 2 seconds to maintain connectivity, this is something that is quite confusing .

**Comment by muhammad-haroon** [comment] 2016-11-28 20:08
Does this have something to do with c99 or c11 compatibility   ?

**Comment by ralight** [comment] 2016-11-28 20:09
You need to set `mosquitto_threaded_set()`. If you haven't got that function, your version of libmosquitto is too old.

**Comment by muhammad-haroon** [comment] 2016-11-28 20:10
ok thanks @ralight

**Comment by ralight** [comment] 2016-12-04 22:21
I'm closing this because I don't think it's directly a problem with mosquitto, more with the version you happen to have installed. If you disagree, please reopen and provide more information.

**Closed by ralight** 2016-12-04 22:21 UTC
