### ISSUE TITLE
IPv6 to IPv4 Fallback

### ISSUE THREAD

**Issue by MyIgel** [eclipse/mosquitto#686] opened 2018-01-31 10:45 UTC
At the moment, if the domain resolves to an IPv4 and IPv6 address for a bridge, it client only tries the v6 address and ignores the v4 record.
It would be nice if the bridge could try to connect to the host via IPv4 if IPv6 fails for some reasons (port blocked or so).
The "Socket error on client [connection], disconnecting." is not really helpful while debugging that problem ;)

**Comment by karlp** [comment] 2018-01-31 11:14
Surely this is a dns issue.  If you are providing addresses in dns that you don't want to be using... stop providing them in dns.  It's pretty unfeasible that _every_ application in the world needs to try and implement their own policy of when and how to pick different dns results.  That's the resolver's job!

**Comment by toast-uz** [comment] 2018-03-03 03:56
@MyIgel is this a duplicate of #574 ?

**Comment by toast-uz** [comment] 2018-04-07 11:47
Closing as duplicated of #574 .

**Closed** 2018-04-07 11:47 UTC
Labels: duplicate, enhancement, mosquitto-broker
