### ISSUE TITLE
mosquitto_passwd 1.6.12

### ISSUE THREAD

**Issue by 1mek** [eclipse/mosquitto#1890] opened 2020-11-12 06:47 UTC
Latest. (1.6.12) Docker.
mosquitto_passwd doesnt work with anything, respond "Killed" to  everything.

**Comment by ralight** [comment] 2020-11-12 16:56
I've tried a few commands ok, could you give an example of how you run it that fails?

**Comment by 1mek** [comment] 2020-11-12 18:54
Well basic install from docker hub. Nothing edited. 
Latest build.

`root@server:~# docker exec -it eclipse-mosquitto_test sh
/ # mosquitto_passwd -c /mosquitto/config/mosquitto.passwd test
Password:
Reenter password:
Killed
/ # echo test:password >> /mosquitto/config/mosquitto.passwd
/ # mosquitto_passwd -U /mosquitto/config/mosquitto.passwd
Killed
/ # mosquitto_passwd -b /mosquitto/config/mosquitto.passwd test testuser
Killed
/ #
`

**Comment by dg1yds** [comment] 2020-11-21 12:33
Exactly the same issue here - also latest install from docker hub.

**Comment by hubient** [comment] 2020-12-06 12:25
Hi same issue for me but also on the mosquitto_sub has the issue in docker.
I connected with more then one possibility.
Once as root to the container and oner as mosquitto user. 
But no change.

It tells only "Killed" as mentioned and no hint to the cause.

**Comment by ralight** [comment] 2020-12-06 16:25
Is this still an issue? I have been unable to reproduce it using the 1.6.12 image `a455d3fe0296`. That image was recreated 2 days ago though, so it is possible there was an issue in the previous image which is no longer present.

**Comment by justpowershell** [comment] 2020-12-13 18:55
Still an issue for me. Using Synology. Switching to OpenSSL fixed.

**Comment by hubient** [comment] 2020-12-13 19:00
I can acknowledge this. I tryed this also today again. Only the openssl version works witout this issue.

**Comment by AbDhops** [comment] 2020-12-16 21:11
Same here... Using version 1.6.12 

```
/ # mosquitto_passwd -b /mosquitto/data/usercnf user password
Killed
```

**Comment by mcmellow** [comment] 2020-12-20 17:02
Same problem here ... Using version 1.6.12 on a Raspberry Pi 3B  (arach64) docker 

```
/ #  mosquitto_passwd -c /DockerData/mosquitto/config/mosquitto.passwd mqtt
Password:
Reenter password:
/ #
```

**Comment by ralight** [comment] 2020-12-20 17:41
@mcmellow That looks correct to me? No `Killed` line. Does the file not get updated.

So far it seems as though this is limited to the libressl based image running on synology only.

**Comment by mcmellow** [comment] 2020-12-21 09:49
> @mcmellow That looks correct to me? No `Killed` line. Does the file not get updated.
> 
> So far it seems as though this is limited to the libressl based image running on synology only.

I use option -c to create a mosquitto.passwd file.   There is no file created and no errors in the log me.

**Comment by aro-git** [comment] 2020-12-28 10:14
Same problem ...
Synology DS 716+, eclipse-mosquitto 1.6.12 in docker, today install

root@DS716:~# docker version
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Fri Mar 13 06:46:11 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       3a371f3
  Built:            Fri Mar 13 06:44:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by nothing-to-see** [comment] 2021-01-04 00:17
problem solved for me using eclipse-mosquitto:2-openssl 
mosquitto_passwd works great

**Comment by jonstelly** [comment] 2021-02-16 20:53
Same issue, synology.  using 2-openssl tagged image works.  Thanks for that.

**Comment by wrightsonm** [comment] 2021-02-22 22:18
Also had this issue running latest.  Changed to the most recent 2-x openssl and problem was resolved!

**Comment by ralight** [comment] 2021-02-24 21:32
Thanks for the reports everyone, I'm glad it is resolved and am going to close this now.

**Closed by ralight** 2021-02-24 21:32 UTC

**Comment by cbrandlehner** [comment] 2021-11-01 08:25
Problem still reproduces with 2.0.13.
Workaround is still to use the OpenSSL image.
