### ISSUE TITLE
TLS fails when the time setting is year 2038

### ISSUE THREAD

**Issue by tassi-yuzukko** [eclipse/mosquitto#2067] opened 2021-02-03 09:38 UTC
Hi.

I want to make it work after 2038, but if I set the date on the PC to 2038 or later, TLS fails.
Actually, the broker works fine, but the client (`mosquitto_sub` and `mosquitto_pub`) does not.

---

My enviroments is belows:

* working on Windows 10 Pro x64
* trying to connect to broker using TLS like below
	* `mosquitto_sub -d -t test -p 8883 --cafile ./certs/ca.crt`
* setting to the time at 01/01/2039 (date that meets the requirements of the 2038 problem)

---

also I got following error messages.

```
# client side
>mosquitto_sub -d -t test -p 8883 --cafile ./certs/ca.crt
Client mosqsub|XXXXXXXXXX sending CONNECT
OpenSSL Error[0]: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: A TLS error occurred.

# broker side
-1643925025: OpenSSL Error[0]: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
-1643925025: Client <unknown> disconnected: Unknown error.
```

I set the `--insecure` option, but it did not work.

I read the source code to detect the cause of this problem and I found the followings.  
(`preverify_ok` is always 0 when I set the date on the PC to 2038 or later)

```
int mosquitto__server_certificate_verify(int preverify_ok, X509_STORE_CTX *ctx)
{
	/* Preverify should have already checked expiry, revocation.
	 * We need to verify the hostname. */
	struct mosquitto *mosq;
	SSL *ssl;
	X509 *cert;

	/* Always reject if preverify_ok has failed. */
	if (!preverify_ok) return 0;	// <- preverify_ok becomes 0 when I set the date on the PC to 2038 or later

	...
}
```

So maybe the OpenSSL is the one, but I could not figure out how to fix this. 

Can anyone help me ?

Thanks.

**Comment by sectokia** [comment] 2021-02-03 23:47
Can you post the details of the cert? The root CA certs have typically been set to expire in 2038.

**Comment by tassi-yuzukko** [comment] 2021-02-04 01:43
@sectokia 
Thanks for your reply.

Actually, the  root CA certs I'm using is a self-signed, and I didn't know that the root CA certs have a typical expiration date. 

So is this problem unavoidable if I use a self-signed certs?  
For my part, I want to make sure that even if I use a self-signed certs, it will still work after 2038.  
In this case, is there no other way but to modify the source code by myself and customize it for my own use? (In other words, there is no planning to support this officially?)

And I run `openssl verify -verbose -CAfile ./certs/ca.crt` when I set to the time at 01/01/2039, but there was no response.

**Comment by sectokia** [comment] 2021-02-04 06:23
Try this and see what the end date is for the cert:
`openssl x509 -enddate -noout -in ./certs/ca.crt`

**Comment by tassi-yuzukko** [comment] 2021-02-04 06:41
I got a following result.

```
>openssl x509 -enddate -noout -in ./ca.crt
notAfter=Jan 29 06:36:13 2121 GMT
```

**Comment by ralight** [comment] 2021-02-04 10:12
Perhaps it is worth checking against `openssl s_server` to see whether the problem is mosquitto or openssl.

I haven't had chance to look at this myself yet.

**Comment by sectokia** [comment] 2021-02-05 00:44
Does this happen for both the 32bit version and the 64bit windows version?

**Comment by tassi-yuzukko** [comment] 2021-02-05 06:24
I only have a 64bit Windows PC, so I can't check how it works on the 32bit version.
However, it is probably certain that this will happen in the 64bit version.

**Comment by sectokia** [comment] 2021-02-07 10:46
What happens if you do:
`openssl verify -trusted ca.crt ca.crt`

**Comment by tassi-yuzukko** [comment] 2021-02-08 23:27
Setting to the time at 02/09/2021 :

```
> openssl verify -verbose -trusted ./certs/ca.crt ./certs/ca.crt
./certs/ca.crt: OK
```

Setting to the time at 02/09/2038 :

```
> openssl verify -verbose -trusted ./certs/ca.crt ./certs/ca.crt
./certs/ca.crt: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = XXXXXXXXX
error 13 at 0 depth lookup:format error in certificate's notBefore field
```

It seems that the problem is on the Openssl side?

**Comment by sectokia** [comment] 2021-02-09 13:06
Based on some comments i’ve seen OpenSSL deliberately uses a time_t 32bit type, and i don’t think anyone is going to care about this for 10 years yet

**Comment by ralight** [comment] 2021-02-09 15:08
I've just tested this on linux and it works as expected - the certificate expiring in 2121 works ok with the date set to 2040.

**Comment by ralight** [comment] 2022-08-12 16:06
I think this is resolved on the mosquitto side, so am closing this issue. If not, please feel free to reopen and add more information.

**Closed by ralight** 2022-08-12 16:06 UTC
