### ISSUE TITLE
Windows SSL_shutdown error

### ISSUE THREAD

**Issue by PitySOFT** [eclipse/mosquitto#289] opened 2016-10-14 12:17 UTC
I'm running Mosquitto 1.4.10 on windows as a service with SSL configuration using OpenSSL 1.0.2j dlls and I get the error below and the client is disconnected.

`OpenSSL Error: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
`

Any idea how to prevent this? Thanks.

**Comment by ralight** [comment] 2017-01-06 00:50
Sorry for the delay replying. 

The only way I can think that this might occur is if a client connects with SSL but doesn't complete the handshake, then there is a delay and the broker times out the client and closes the socket.

Can you remember how this error message appeared?

**Comment by PitySOFT** [comment] 2017-01-06 07:31
I moved the server on Linux and I have no problems. It seems there is a problem with the Windows version of Mosquitto or OpenSSL. The clients have the same configuration.

**Comment by ralight** [comment] 2017-01-06 08:50
Ok, thanks for the update I'll try and have a look at it. What client were you using?

**Comment by PitySOFT** [comment] 2017-01-06 08:52
Is a library for C# http://www.hivemq.com/blog/mqtt-client-library-encyclopedia-m2mqtt

**Comment by ralight** [comment] 2017-01-06 08:56
Thanks.

**Comment by sre** [comment] 2017-03-09 19:21
I could reproduce this with mosquitto 1.4.10 from Debian testing. Client was also using libmosquitto 1.4.10 and also running on Linux (arm). My client exited quickly due to an unrelated bug retrying and dying every few minutes. As a result the whole mosquitto server became very unstable. I have not yet checked the mosquitto code, but maybe something like the Nginx solution could be used?

http://hg.nginx.org/nginx/rev/062c189fee20

**Comment by ralight** [comment] 2022-08-10 21:13
I'm closing this issue because it relates to 1.4.x and that is now very old, and there have been significant changes in this area. If this is still an issue on more recent versions please create a new issue.

**Closed by ralight** 2022-08-10 21:13 UTC
