### ISSUE TITLE
very unstable, server crashes again and again

### ISSUE THREAD

**Issue by OliverSanftleben** [eclipse/mosquitto#319] opened 2016-11-23 13:12 UTC
Hello,

mosquitto server seems to run very unstable after a while, I have always to restart it periodically.

I have one publisher and two subscribers per websocket, the log says:

...
 Sending PUBLISH to web_44 (d0, q0, r0, m0, 'germany/bikesharing/stations/2231@CallABike', ... (1368 bytes))
1479905611: Sending PUBLISH to web_92 (d0, q0, r0, m0, 'germany/bikesharing/stations/2231@CallABike', ... (1368 bytes))
1479905611: Received PUBLISH from genericCacheDEV1479823686898 (d0, q0, r0, m0, 'germany/bikesharing/stations/2528@CallABike', ... (3609 bytes))
1479905611: Sending PUBLISH to web_44 (d0, q0, r0, m0, 'germany/bikesharing/stations/2528@CallABike', ... (3609 bytes))
1479905611: Sending PUBLISH to web_92 (d0, q0, r0, m0, 'germany/bikesharing/stations/2528@CallABike', ... (3609 bytes))
1479905615: New client connected from 10.10.16.11 as web_24 (c1, k60, u'gcread').
1479905615: Sending CONNACK to web_24 (0, 0)
1479905615: Received SUBSCRIBE from web_24
1479905615:     germany/# (QoS 0)
1479905615: web_24 0 germany/#
1479905615: Sending SUBACK to web_24
1479905617: Socket error on client <unknown>, disconnecting.
1479905617: Socket error on client web_44, disconnecting.
1479905617: Socket error on client <unknown>, disconnecting.
1479905640: Received PUBLISH from genericCacheDEV1479823686898 (d0, q0, r0, m0, 'germany/arrivals/urbanPublicTransport', ... (0 bytes))
1479905640: Sending PUBLISH to web_92 (d0, q0, r0, m0, 'germany/arrivals/urbanPublicTransport', ... (0 bytes))
1479905640: Sending PUBLISH to web_24 (d0, q0, r0, m0, 'germany/arrivals/urbanPublicTransport', ... (0 bytes))
...
1479905640: Received PUBLISH from genericCacheDEV1479823686898 (d0, q0, r0, m0, 'germany/arrivals/urbanPublicTransport/BVG_9023201_M49_2016-11-23_13:49:00', ... (109 bytes))
1479905640: Sending PUBLISH to web_92 (d0, q0, r0, m0, 'germany/arrivals/urbanPublicTransport/BVG_9023201_M49_2016-11-23_13:49:00', ... (109 bytes))
[1]+  Exit 139                sudo su -s /bin/bash -c 'mosquitto -c /etc/mosquitto/mosquitto.conf -v' mosquitto

There are no more log entries, why the crash happened.

I'm using mosquitto 1.4.9 on Ubuntu 16.04.

**Comment by ralight** [comment] 2016-12-04 22:26
I have really struggled to reproduce this but have now been able to do it consistently. It looks as though the problem is related to the libwebsockets binary in ubuntu. I couldn't reproduce it at first because I had a separate version of libwebsockets (1.7.x) installed not from ubuntu. Even recompiling the version which is in ubuntu myself doesn't result in any crashes.

I'm not really sure what the general solution is here, it seems a bit out of my control. Could you try compiling your own version of libwebsockets though?

**Comment by ralight** [comment] 2016-12-04 22:40
I'm pretty certain this is a duplicate of #303, so I'm closing this and we should carry on discussing it there.

**Closed by ralight** 2016-12-04 22:40 UTC
