### ISSUE TITLE
"conf.d" configuration files should be able to supersede mosquitto.conf settings

### ISSUE THREAD

**Issue by C-Duv** [eclipse/mosquitto#560] opened 2017-09-22 16:33 UTC
I think the settings that are defined in files residing in `/etc/mosquitto/conf.d` should overtake any settings present in  `/etc/mosquitto/mosquitto.conf`.

The `/etc/mosquitto/mosquitto.conf` file says "Place your local configuration in /etc/mosquitto/conf.d/", but if I want to change persistence location by having the following `/etc/mosquitto/conf.d/external_persistence.conf` file:

    persistence_location /mnt/some-disk/mqtt

I get the following error when running Mosquitto:

> Error: Duplicate persistence_location value in configuration.
> Error found at /etc/mosquitto/conf.d/external_persistence:1.
> Error found at /etc/mosquitto/mosquitto.conf:13.
> Error: Unable to open configuration file.

In a more general way: any configuration file (being the one given via `-c` option of `mosquitto` or any file loaded via `include_dir`) should be able to overtake whatever the previous files had set mosquitto settings to (it will be up to the user to make it coherent).

**Comment by toast-uz** [comment] 2017-09-22 21:48
I think the current behavior is quite normal as the meaning of "include" of common programming languages. Could you show some examples of major software operate as your wish? Apache http server and Nginx http server has similar "include" directives. If they operate as your wish, your thought will be considerable.

**Comment by toast-uz** [comment] 2018-03-02 13:32
Closing because no information for a long time. If you have any information, post at mosquitto-dev ML before the issue is classified as a bug.

**Closed by toast-uz** 2018-03-02 13:32 UTC
