### ISSUE TITLE
Sending PUBREC to local.CTRLS-BRIDGE-USER

### ISSUE THREAD

**Issue by nikhilve99** [eclipse/mosquitto#401] opened 2017-03-09 04:08 UTC
hi,
 i am facing an issue where my other bridge server contineouly sending an error "**## **Sending PUBREC to local.BRIDGE-USER (Mid: 942)
1489031098: Socket error on client local.BRIDGE-USER, disconnecting****"

kindly help me out why we are getting this msg and also provide the solution too.

Regards
Nikhil

**Comment by ralight** [comment] 2017-07-20 15:05
This could be caused by an incomplete QoS 2 message flow that one broker knows about (the one initiating the PUBREC) but that the other broker does not, hence it rejects it.

This problem was fixed in version 1.4.9.

**Comment by PierreF** [comment] 2018-01-05 17:26
Do you still have this issue with Mosquitto 1.4.9 or newer ?

**Comment by ralight** [comment] 2021-01-08 18:23
I presume this is fixed, if not please reopen and add more information.

**Closed by ralight** 2021-01-08 18:23 UTC
Labels: need-more-information
