### ISSUE TITLE
Strange behavior with mqtt + websocket on Mac

### ISSUE THREAD

**Issue by mansj** [eclipse/mosquitto#1527] opened 2019-12-10 10:20 UTC
I'm running mosquitto 1.6.8 installed via homebrew on Mac OS X High Sierra. 

I need to have connectivity both from python clients and javascript clients, so I have two listeners activated - one mqtt on port 1883 and one websockets on port 9001.

Things are working fine, and clients can connect, subscribe and publish as intended, except that after a short period of time (undetermined - more than 60 seconds, less than one hour) a strange behaviour appears that I can't get to the root of.

Publishing to the mqtt listeners seems to work, but no clients are seeing the updates UNTIL I refresh the Javascript client connection.

So I can publish messages from my python client, no error messages. But no clients - not python clients nor JS clients - see anything in their subscriptions. It's dead. 

If I then hit "refresh" in a web browser with a JS client, the messages suddenly "pop up" in all subscribed clients - python clients as well as JS clients. It would appear that messages are for some reason held back until the JS client reconnects. 

What could cause this behaviour? Is there some sort of blocking from the JS client?

**Comment by DexterLB** [comment] 2019-12-15 19:25
I am experiencing the same issue.

Also, the following behaviour on another device, which might be related: running mosquitto with no websockets enabled works normally with negligible latency. Simply enabling websockets (even without connected clients) causes the latency on the TCP listener to go up to tens of seconds.

**Comment by ralight** [comment] 2019-12-16 00:53
What version of libwebsockets are you using?

**Comment by DexterLB** [comment] 2019-12-16 08:36
In both cases it's `libwebsockets-3.2.0` and mosquitto master (`6bfd52af9`).
I forgot to mention that both devices are Linux (so this is not a mac-exclusive problem), one of them is x86_64 and the other is a raspberry pi (armv6h)

**Comment by mansj** [comment] 2019-12-16 08:50
In my case, I "solved" it by moving from a Mac to Raspberry Pi. My take is that there is something on the Mac, possibly, that interferes with running the websocket server as a service. After about 10 minutes, the log files quits showing pings and other traffic, to only update once per minute. That means that all messages, pings, etc are processed exactly once every 60 seconds.

**Comment by DexterLB** [comment] 2019-12-16 15:20
Maybe the two are separate issues, but here is some extra info:
- strace doesn't show a hang in any system call (I ran the mosquitto process for 10sec, sent 1 message and waited for it to be received. The latency was 6sec, and the total time spent in syscalls was about 90ms - negligible)
- the user time was also negligible: about 100ms. All that latency seems to be spent in idle?

**Comment by ralight** [comment] 2019-12-16 23:38
libwebsockets 3.2.0 introduced a breaking change in its behaviour which sounds as though is the cause here. I did think that 1.6.8 should work fine with 3.2.0, but perhaps there is some reason why it is not doing so on the homebrew builds. If you are able, I would suggest moving to libwebsockets 3.1.0 (or older, up to 2.4.x) which should completely remove the problem. I will have to have another look at it.

**Comment by DexterLB** [comment] 2019-12-17 12:05
Indeed, using libwebsockets 2.4.2 fixes all problems!

**Comment by DexterLB** [comment] 2019-12-17 14:47
I was too hasty: while using libwebsockets 2.4.2 fixes the latency problems, I now can't connect to the websocket from firefox via the paho javascript library: I get `AMQJSC0001E Connect timed out.`.

**Comment by Auswaschbar** [comment] 2020-01-17 10:37
Just FYI, this bug also occurs in the alpine 3.11 packets. They use mosquitto 1.6.8 and libwebsockets 3.2.0.

**Comment by ralight** [comment] 2021-01-08 23:57
This was already resolved, but I'll add a note - I reported the issue for lws 3.2.0, and it was fixed in 3.2.1. Later versions of Mosquitto also got a workaround for 3.2.0, so this should be fixed for all combinations.

**Closed by ralight** 2021-01-08 23:57 UTC
