### ISSUE TITLE
How to fix it " Unable to load server key file"??

### ISSUE THREAD

**Issue by vishuPPatel** [eclipse/mosquitto#873] opened 2018-07-02 09:02 UTC
hello...friend 

How to fix it!!!...

1530521912: mosquitto version 1.4.15 (build date Wed, 28 Feb 2018 11:29:47 +0000) starting
1530521912: Config loaded from /etc/mosquitto/mosquitto.conf.
1530521912: Opening ipv4 listen socket on port 1883.
1530521912: Opening ipv6 listen socket on port 1883.
1530521912: Opening ipv4 listen socket on port 8883.
1530521912: Opening ipv6 listen socket on port 8883.
1530521912: Error: Unable to load server key file "/etc/mosquitto/certs/server.key". Check keyfile.

Thansk!!...

**Comment by toast-uz** [comment] 2018-07-27 11:04
Please change the subject If you insist on reporting a bug for mosquitto. This place is not for a question. Use mosquitto-dev before you are sure for the bug. Look at the instruction (https://mosquitto.org/).

**Comment by ralight** [comment] 2018-08-01 20:37
You could check:

Does /etc/mosquitto/certs/server.key exist?
Does the mosquitto user have read access to /etc/mosquitto/certs/server.key ?
Are you sure the server key has been generated properly?

If you can, then using the latest code from the `fixes` branch will print out more error information about what the problem is.

**Comment by toast-uz** [comment] 2018-09-09 03:49
Closing as no information for a long time. Feel free to reopen if you are having this issue yet.

**Closed by toast-uz** 2018-09-09 03:49 UTC
Labels: need-more-information
