### ISSUE TITLE
Denied PUBLISH error

### ISSUE THREAD

**Issue by edwindvinas** [eclipse/mosquitto#178] opened 2016-05-30 23:47 UTC
Hi everyone! I got some error on Mosquitto server which suggests it can't publish data from my sensor. Any idea how to fix this?
```
Denied PUBLISH from ttnhdl-xxxxxxxxxxx (d0, q2, r0, m1, 'XXXXXXXXXXXXXXXX/devices/XXXXXXXXXXXXXXXX/up', ... (432 bytes))
Sending PUBREC to ttnhdl-FBjXbqcoJsWtYaKz (Mid: 1)
```

Btw, I am using Mosquitto and already got the mosquitto.conf, jp.acl and jp.pw running. What do you think causes this error? Is it something related to conf file or acl file?

Reference:
http://staging.thethingsnetwork.org/wiki/Backend/Connect/Application

I have this acl topic entries:
pattern $SYS/%c/devices/%c/up
pattern $SYS/%c/devices/%c/down
pattern $SYS/%c/devices/%c/activations

Thanks!

**Comment by ralight** [comment] 2016-06-01 08:17
I've just tested this and it works for me - but you do have missing information in the publish (the xxxxx). I've assumed that `XXXXXXXXXXXXXXXX/devices/XXXXXXXXXXXXXXXX/up` is actually `$SYS/<clientid>/devices/<clientid>up`

I'd say the problem is that your topic doesn't match an ACL. Without more details it is impossible to say any more though.

**Comment by ralight** [comment] 2016-06-30 10:32
I'm closing this because there is no more information.

**Closed by ralight** 2016-06-30 10:32 UTC
Labels: need-more-information
