### ISSUE TITLE
Error creating bridge: Unknown error. version 1.5.4

### ISSUE THREAD

**Issue by bayuTam** [eclipse/mosquitto#1054] opened 2018-11-24 15:32 UTC
I try to make bridge connection on windows (mosquitto v1.5.4),  error description **is unknow error.**
this success with v1.4.14 bridge connection to _test.mosquitto.org_

**Comment by ralight** [comment] 2018-11-28 22:18
Could you share your configuration please?

**Comment by ralight** [comment] 2018-12-04 21:43
I'm closing this as a duplicate of #1064, I realise you were the first to report but there is a bit more information in the other report, I hope you don't mind.

**Closed by ralight** 2018-12-04 21:43 UTC

**Comment by bayuTam** [comment] 2018-12-04 23:01
I'm sorry before, I only got an internet connection since 2 days. I hope can reply to this message.

By Bayu t.a.m. 
 
  On Wed, Dec 5, 2018 at 5:43, Roger Light<notifications@github.com> wrote:   
Closed #1054.
