### ISSUE TITLE
mosquitto_connect_async | Failing with MOSQ_ERR_ERRNO (14) [errno 57 = Socket is not connected]

### ISSUE THREAD

**Issue by tahasamad** [eclipse/mosquitto#365] opened 2017-02-01 13:27 UTC
Version: 1.4.10
IDE: Version 8.1
OS: OS X El Capitan

Regarding following code:

```
#include <stdio.h>
#include <mosquitto.h>
#include <stdbool.h>

int main(int argc, const char * argv[]) {
    // insert code here...
    printf("Hello, World!\n");
    
    struct mosquitto* mosq = mosquitto_new(NULL, true, NULL);
    mosquitto_username_pw_set(mosq, "<username>", "<password>");
    int error = mosquitto_connect_async(mosq, "<host>", 1883, 60);
    //int error = mosquitto_connect(mosq, "<host>", 1883, 60);
    printf("Error Code: %d %s\n", error, mosquitto_strerror(error));
    
    return 0;
}
```

I get log: `Error Code: 14 Socket is not connected`. While when using synchronous version of connect, with everything else being same 0 (Success/No Error) is returned.

But with same code using synchronous version everything works fine.

**Comment by PierreF** [comment] 2018-01-05 17:06
Closing as duplicate of #373. If you think this is a different issue, feel free to reopen.

**Closed by PierreF** 2018-01-05 17:06 UTC
