### ISSUE TITLE
libwebsockets.h missing from the src directory

### ISSUE THREAD

**Issue by Yvanttt** [eclipse/mosquitto#583] opened 2017-10-12 05:37 UTC
Header file libwebsockets.h is not found in the pacakge.

compile fails as it is needed by these files.

loop.c 
mosquito.c 
mosquitto_broker.h
read_handle_server.c
websockets.c

**Comment by Tifaifai** [comment] 2017-10-12 07:53
It's normal. You must install libwebsockets package on ubuntu distribution.

**Comment by toast-uz** [comment] 2017-10-12 13:09
@Tifaifai is right that mosquitto is normal.
@Yvanttt, generally, you must install the development package to compile with the library.
For libwebsockets, you must prepare the development package named as libwebsocket-dev or libwebsocket-devel.

**Comment by trojanc** [comment] 2017-12-04 20:10
How I built libwebsockets before building mosquitto...if it is of any use to anyone...

```
git clone -b v2.4.1 https://github.com/warmcat/libwebsockets.git
cd libwebsockets
mkdir build
cd build
cmake .. -DLIB_SUFFIX=64
make
make install
```
After this, build mosquitto

**Comment by toast-uz** [comment] 2017-12-04 22:55
You can find  libwebsockets.h in libwebsockets/lib while not in mosquitto.

**Comment by Tifaifai** [comment] 2017-12-05 07:17
Do you make a  cross compilation ?
In my case, i have rewrite 'config.mk' and modify the file with for libwebsockets, for example :
```
ifeq ($(WITH_WEBSOCKETS),yes)
  BROKER_CFLAGS:=$(BROKER_CFLAGS) -I/opt/crosstool-ng/arm-linux-gnueabi/include -I/opt/libwebsockets-2.4.1/include -DWITH_WEBSOCKETS
  BROKER_LIBS:=$(BROKER_LIBS) -L/opt/crosstool-ng/arm-linux-gnueabi/lib/ -lz -L/opt/libwebsockets-2.4.1/lib -lwebsockets
endif
```

if it might help a little bit ...

**Comment by toast-uz** [comment] 2017-12-06 12:04
@trojanc first you search libwebsockets.h in your environment. It was installed definitely by "make install" of libwebsockets. Then try the way of @Tifaifai or #245 .

**Comment by ralight** [comment] 2017-12-22 00:12
I'm closing this issue because it's not a bug with mosquitto. If you are having problems getting this sorted, I'd suggest trying the mailing list.

**Closed by ralight** 2017-12-22 00:12 UTC
Labels: not a bug

**Comment by jeroenst** [comment] 2019-07-12 15:03
apt install libwebsockets-dev
