### ISSUE TITLE
Mosquitto v1.5.1 on Windows uses a lot of CPU

### ISSUE THREAD

**Issue by gbr8cke** [eclipse/mosquitto#943] opened 2018-08-31 07:47 UTC
On a machine with 2 cores, Mosquitto uses between 40 - 50% CPU of the complete machine. With previous versions, it almost didn't consume any CPU load. I don't think this is normal. Can somebody check this?
Thanks a lot!

**Comment by wiebeytec** [comment] 2018-09-04 09:48
How many clients do you have? Because 50% is 100% of one core, I suspect you may be affected by #948.

**Comment by gbr8cke** [comment] 2018-09-05 08:14
I don't have a lot of clients. I Publish/Subscribe with max. 5 clients. If I revert to the previous version, I don't have any CPU load - so for me it's really this version that causes the high CPU load.

**Comment by gbr8cke** [comment] 2018-09-08 12:36
Does anybody has the same issues on Windows?

**Comment by kiranpradeep** [comment] 2018-09-08 13:41
@wiebeytec  I download and installed 1.5.1 (64 bit) on Win 10 Home(1803). I installed as service only to see if it crashes.  **I didn't start any clients at all**. CPU utilization was high at 30% on Core i5.  I am sorry, I can't provide logs as I now moved to 1.4.9 to see how it behaves. But this issue exists and is not related to clients.

**Comment by toast-uz** [comment] 2018-09-09 00:54
@gbr8cke , @kiranpradeep , could you try only to run "mosquitto.exe -v" on command prompt? I tried it on Win10 Pro(32bit, 1511) on VirtualBox, but the issue was not reproduced. I'will update Windows and retry soon later.

**Comment by toast-uz** [comment] 2018-09-09 03:40
I've reproduced after updating to Windows 10 Pro (32bit, 1803). I guess something wrong in mosquitto appeared.

**Comment by toast-uz** [comment] 2018-09-13 13:09
p.s.
There are many issues for CPU usage on Windows 10-1803. But, this seems different from them because it occurs while mosquitto runs.

**Comment by km3** [comment] 2018-09-13 20:04
Have same problem on Windows with ver. 1.5.1.
On win 10, i3 with 4 core eat 30% of CPU, on win 2016 server with 2 core eat 50% of CPU.
Do not have connection at all.
They don't use .net. 
I'm compile it using VC c++, only use vc_redist libs.

**Comment by km3** [comment] 2018-09-14 13:08
Check on mosquitto-1.4.15-install-win32 - normal use of CPU: 0%

**Comment by KHouse75** [comment] 2018-09-20 18:14
I can confirm that I also have the same 40% to 50% CPU usage with 1.5.1 32 bit and 64 bit running on Windows 7.  I switched back to 1.4.15 and it shows 0% CPU.

**Comment by saqirltu** [comment] 2018-09-24 13:08
Still experiencing the same with v1.5.2 both on Win7 64 and Win10 64.

**Comment by ralight** [comment] 2018-09-25 09:38
This is fixed by the pull request in #971, which will be in 1.5.3 shortly.

**Closed** 2018-09-25 15:16 UTC
Labels: bug, mosquitto-broker
